import { describe, expect, it } from 'vitest'
import { isGeneratedFile } from './generatedFile'

describe('isGeneratedFile', () => {
  it('recognises dependency locks', () => {
    for (const path of ['Cargo.lock', 'web/package-lock.json', 'pnpm-lock.yaml', 'ios/Package.resolved', 'uv.lock']) {
      expect(isGeneratedFile(path), path).toBe(true)
    }
  })

  it('recognises generated names and directories', () => {
    for (const path of ['src/api.generated.ts', 'src/routeTree.gen.ts', 'proto/user.pb.go', 'lib/model.g.dart', 'src/generated/client.ts']) {
      expect(isGeneratedFile(path), path).toBe(true)
    }
  })

  it('recognises conventional generated-file banners when line one is available', () => {
    expect(isGeneratedFile('src/client.ts', '/* generated using OpenAPI - do not edit */')).toBe(true)
    expect(isGeneratedFile('models.go', '// Code generated by sqlc. DO NOT EDIT.')).toBe(true)
  })

  it('keeps ordinary source reviewable', () => {
    for (const path of ['src/generator.ts', 'internal/general/store.go', 'docs/generated-files.md', 'go.mod']) {
      expect(isGeneratedFile(path), path).toBe(false)
    }
  })
})
