// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apitypes

// Defines values for AgentStatus.
const (
	Ended    AgentStatus = "ended"
	Exited   AgentStatus = "exited"
	Pending  AgentStatus = "pending"
	Starting AgentStatus = "starting"
	Unknown  AgentStatus = "unknown"
	Waiting  AgentStatus = "waiting"
)

// AgentResponse defines model for AgentResponse.
type AgentResponse struct {
	AgentStatus     *AgentStatusInfo `json:"agent_status,omitempty"`
	AgentType       string           `json:"agent_type"`
	BaseBranch      string           `json:"base_branch"`
	BranchName      *string          `json:"branch_name"`
	ContainerId     string           `json:"container_id"`
	ContainerStatus string           `json:"container_status"`
	Id              string           `json:"id"`
	PrePrompt       string           `json:"pre_prompt"`
	ProjectPath     string           `json:"project_path"`
	Prompt          string           `json:"prompt"`
	WorktreePath    *string          `json:"worktree_path"`
}

// AgentStatus The hook-reported status of the agent session
type AgentStatus string

// AgentStatusInfo defines model for AgentStatusInfo.
type AgentStatusInfo struct {
	// Event The hook event that triggered this status (SessionStart, Stop, SessionEnd, or polling)
	Event *string `json:"event,omitempty"`

	// LastMessage Last assistant message (only present on Stop events)
	LastMessage *string `json:"last_message,omitempty"`

	// Reason Session end reason (only present on SessionEnd events)
	Reason *string `json:"reason,omitempty"`

	// Status The hook-reported status of the agent session
	Status AgentStatus `json:"status"`

	// Timestamp ISO 8601 timestamp of when the status was set
	Timestamp string `json:"timestamp"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// SpawnAgentRequest defines model for SpawnAgentRequest.
type SpawnAgentRequest struct {
	// AgentType Agent type: claude or gemini
	AgentType *string `json:"agent_type,omitempty"`

	// BaseBranch Base branch to create the worktree from (defaults to current branch)
	BaseBranch *string `json:"base_branch,omitempty"`

	// Id Unique identifier for the agent (slug format, max 40 chars)
	Id string `json:"id"`

	// Prompt The prompt to give to the agent
	Prompt string `json:"prompt"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// ProjectRoot Absolute path to the project root
	ProjectRoot *string `json:"project_root,omitempty"`
	Status      *string `json:"status,omitempty"`

	// UptimeSeconds Seconds since the server started
	UptimeSeconds *float32 `json:"uptime_seconds,omitempty"`
	Version       *string  `json:"version,omitempty"`
}

// SpawnAgentJSONRequestBody defines body for SpawnAgent for application/json ContentType.
type SpawnAgentJSONRequestBody = SpawnAgentRequest
