//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for AgentStatus.
const (
	Building AgentStatus = "building"
	Killing  AgentStatus = "killing"
	Merging  AgentStatus = "merging"
	Pending  AgentStatus = "pending"
	Running  AgentStatus = "running"
	Starting AgentStatus = "starting"
	Stopped  AgentStatus = "stopped"
	Waiting  AgentStatus = "waiting"
)

// Defines values for DiffFileChangeType.
const (
	Added    DiffFileChangeType = "added"
	Deleted  DiffFileChangeType = "deleted"
	Modified DiffFileChangeType = "modified"
	Renamed  DiffFileChangeType = "renamed"
)

// Defines values for DiffLineType.
const (
	Addition  DiffLineType = "addition"
	Context   DiffLineType = "context"
	Deletion  DiffLineType = "deletion"
	NoNewline DiffLineType = "no_newline"
)

// Defines values for ErrorResponseError.
const (
	DockerConnect ErrorResponseError = "docker_connect"
	InternalError ErrorResponseError = "internal_error"
	NotFound      ErrorResponseError = "not_found"
	Unauthorized  ErrorResponseError = "unauthorized"
)

// Defines values for MergeConflictErrorError.
const (
	MergeConflict MergeConflictErrorError = "merge_conflict"
)

// Defines values for TerminalDataEventType.
const (
	TerminalDataEventTypeBuildFinished TerminalDataEventType = "build_finished"
	TerminalDataEventTypeData          TerminalDataEventType = "data"
	TerminalDataEventTypeStatus        TerminalDataEventType = "status"
)

// Defines values for TerminalEventType.
const (
	TerminalEventTypeBuildFinished TerminalEventType = "build_finished"
	TerminalEventTypeData          TerminalEventType = "data"
	TerminalEventTypeStatus        TerminalEventType = "status"
)

// Defines values for TerminalStatusEventType.
const (
	BuildFinished TerminalStatusEventType = "build_finished"
	Data          TerminalStatusEventType = "data"
	Status        TerminalStatusEventType = "status"
)

// Defines values for GetConfigParamsScope.
const (
	GetConfigParamsScopeProject GetConfigParamsScope = "project"
	GetConfigParamsScopeUser    GetConfigParamsScope = "user"
)

// Defines values for SaveConfigParamsScope.
const (
	SaveConfigParamsScopeProject SaveConfigParamsScope = "project"
	SaveConfigParamsScopeUser    SaveConfigParamsScope = "user"
)

// AddProjectRequest defines model for AddProjectRequest.
type AddProjectRequest struct {
	// Path Absolute filesystem path to the project root (must be a git repository)
	Path string `json:"path"`
}

// AgentConfig defines model for AgentConfig.
type AgentConfig struct {
	Context              *string   `json:"context"`
	Dockerfile           *string   `json:"dockerfile"`
	DockerfileContents   *string   `json:"dockerfile_contents"`
	DockerignoreContents *string   `json:"dockerignore_contents"`
	PrePrompt            *string   `json:"pre_prompt"`
	SharedMounts         *[]string `json:"shared_mounts"`
}

// AgentInputRequest defines model for AgentInputRequest.
type AgentInputRequest struct {
	// Text Text to send to the agent's stdin (a newline is appended automatically)
	Text string `json:"text"`
}

// AgentResponse defines model for AgentResponse.
type AgentResponse struct {
	AgentStatus     *AgentStatusInfo `json:"agent_status,omitempty"`
	AgentType       string           `json:"agent_type"`
	BaseBranch      string           `json:"base_branch"`
	BranchName      *string          `json:"branch_name"`
	ContainerId     string           `json:"container_id"`
	ContainerStatus string           `json:"container_status"`

	// CreatedAt Unix timestamp (seconds) when the container was created/started; 0 if no container
	CreatedAt *int64 `json:"created_at,omitempty"`

	// Ephemeral If true, the agent is temporary and its container will be removed on stop.
	Ephemeral    *bool   `json:"ephemeral,omitempty"`
	Id           string  `json:"id"`
	PrePrompt    string  `json:"pre_prompt"`
	ProjectPath  string  `json:"project_path"`
	Prompt       string  `json:"prompt"`
	WorktreePath *string `json:"worktree_path"`
}

// AgentStatus The computed status of the agent (derived from container, agent, and head status)
type AgentStatus string

// AgentStatusInfo defines model for AgentStatusInfo.
type AgentStatusInfo struct {
	// Event The hook event that triggered this status (SessionStart, Stop, SessionEnd, or polling)
	Event *string `json:"event,omitempty"`

	// LastMessage Last assistant message (only present on Stop events)
	LastMessage *string `json:"last_message,omitempty"`

	// Reason Session end reason (only present on SessionEnd events)
	Reason *string `json:"reason,omitempty"`

	// Status The computed status of the agent (derived from container, agent, and head status)
	Status AgentStatus `json:"status"`

	// Timestamp ISO 8601 timestamp of when the status was set
	Timestamp string `json:"timestamp"`
}

// CommitInfo defines model for CommitInfo.
type CommitInfo struct {
	AuthorEmail string `json:"author_email"`
	AuthorName  string `json:"author_name"`

	// Message Full commit message
	Message string `json:"message"`

	// Sha Full 40-character commit SHA
	Sha string `json:"sha"`

	// ShortSha Abbreviated 7-character commit SHA
	ShortSha string `json:"short_sha"`

	// Subject First line of the commit message
	Subject *string `json:"subject,omitempty"`

	// Timestamp ISO 8601 timestamp of the author date
	Timestamp string `json:"timestamp"`
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse struct {
	Agents map[string]AgentConfig `json:"agents"`

	// DefaultDockerfiles Built-in default Dockerfiles for each agent type (read-only)
	DefaultDockerfiles *map[string]string `json:"default_dockerfiles,omitempty"`

	// DefaultPrePrompt Built-in default pre-prompt always prepended to agent prompts (read-only)
	DefaultPrePrompt *string     `json:"default_pre_prompt,omitempty"`
	Defaults         AgentConfig `json:"defaults"`
	Features         *struct {
		TerminalBash *bool `json:"terminal_bash,omitempty"`
	} `json:"features,omitempty"`
}

// DiffFile defines model for DiffFile.
type DiffFile struct {
	// Additions Number of added lines
	Additions int `json:"additions"`

	// Binary True if this is a binary file
	Binary     bool               `json:"binary"`
	ChangeType DiffFileChangeType `json:"change_type"`

	// Deletions Number of deleted lines
	Deletions int        `json:"deletions"`
	Hunks     []DiffHunk `json:"hunks"`

	// OldPath Original file path (only set for renamed files)
	OldPath *string `json:"old_path"`

	// Path File path (new path for renamed files)
	Path string `json:"path"`
}

// DiffFileChangeType defines model for DiffFile.ChangeType.
type DiffFileChangeType string

// DiffHunk defines model for DiffHunk.
type DiffHunk struct {
	// Header The @@ ... @@ hunk header line
	Header string     `json:"header"`
	Lines  []DiffLine `json:"lines"`

	// NewStart Starting line number in the new file
	NewStart int `json:"new_start"`

	// OldStart Starting line number in the old file
	OldStart int `json:"old_start"`
}

// DiffLine defines model for DiffLine.
type DiffLine struct {
	// Content Line content without the diff prefix character
	Content string `json:"content"`

	// NewLineNum Line number in the new file (null for deletions)
	NewLineNum *int `json:"new_line_num"`

	// OldLineNum Line number in the old file (null for additions)
	OldLineNum *int `json:"old_line_num"`

	// Type context: unchanged line; addition: added line; deletion: removed line; no_newline: no newline at end of file
	Type DiffLineType `json:"type"`
}

// DiffLineType context: unchanged line; addition: added line; deletion: removed line; no_newline: no newline at end of file
type DiffLineType string

// DiffResponse defines model for DiffResponse.
type DiffResponse struct {
	// BaseCommit Details of the base commit (if a specific commit SHA was given)
	BaseCommit *CommitInfo `json:"base_commit"`

	// BaseRef The base ref used for this diff
	BaseRef string `json:"base_ref"`

	// ConflictFiles List of files with merge conflicts (populated when merge_conflict is true)
	ConflictFiles *[]string  `json:"conflict_files,omitempty"`
	Files         []DiffFile `json:"files"`

	// HeadCommit Details of the head commit
	HeadCommit *CommitInfo `json:"head_commit"`

	// HeadRef The head ref used for this diff
	HeadRef string `json:"head_ref"`

	// MergeConflict True if there are merge conflicts between base_ref and head_ref
	MergeConflict *bool `json:"merge_conflict,omitempty"`

	// UncommittedChanges True if there are uncommitted changes in the worktree
	UncommittedChanges *bool               `json:"uncommitted_changes,omitempty"`
	UncommittedSummary *UncommittedSummary `json:"uncommitted_summary,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Details Human-readable error description
	Details string `json:"details"`

	// Error Machine-readable error type (e.g. internal_error, not_found, unauthorized, docker_connect)
	Error ErrorResponseError `json:"error"`
}

// ErrorResponseError Machine-readable error type (e.g. internal_error, not_found, unauthorized, docker_connect)
type ErrorResponseError string

// MergeConflictError defines model for MergeConflictError.
type MergeConflictError struct {
	// Code HTTP status code
	Code int `json:"code"`

	// Details Human-readable error description
	Details string                  `json:"details"`
	Error   MergeConflictErrorError `json:"error"`
}

// MergeConflictErrorError defines model for MergeConflictError.Error.
type MergeConflictErrorError string

// ProjectInfo defines model for ProjectInfo.
type ProjectInfo struct {
	// Id Unique project identifier (derived from folder name)
	Id string `json:"id"`

	// Name Human-readable project name (last path component)
	Name string `json:"name"`

	// Path Absolute filesystem path to the project root
	Path string `json:"path"`

	// Uuid Persistent project UUID
	Uuid string `json:"uuid"`
}

// SpawnAgentRequest defines model for SpawnAgentRequest.
type SpawnAgentRequest struct {
	// AgentType Agent type: claude, gemini, or bash
	AgentType *string `json:"agent_type,omitempty"`

	// BaseBranch Base branch to create the worktree from (defaults to current branch)
	BaseBranch *string `json:"base_branch,omitempty"`

	// Ephemeral If true, the agent is temporary and its container will be removed on stop.
	Ephemeral *bool `json:"ephemeral,omitempty"`

	// Id Unique identifier for the agent (slug format, max 40 chars)
	Id string `json:"id"`

	// Prompt The prompt to give to the agent
	Prompt *string `json:"prompt,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// DefaultProjectId Project ID of the default (CWD) project
	DefaultProjectId *string `json:"default_project_id,omitempty"`

	// Development Whether the server is running in development mode
	Development *bool `json:"development,omitempty"`

	// DockerError Error message if there is an issue connecting to Docker
	DockerError *string `json:"docker_error"`
	Features    *struct {
		// TerminalBash Whether the bash terminal feature is enabled
		TerminalBash *bool `json:"terminal_bash,omitempty"`
	} `json:"features,omitempty"`

	// ProjectRoot Absolute path to the default project root (server CWD)
	ProjectRoot *string `json:"project_root,omitempty"`
	Status      *string `json:"status,omitempty"`

	// UptimeSeconds Seconds since the server started
	UptimeSeconds *float32 `json:"uptime_seconds,omitempty"`
	Version       *string  `json:"version,omitempty"`
}

// TerminalDataEvent defines model for TerminalDataEvent.
type TerminalDataEvent struct {
	// Data Base64 encoded binary data or plain string
	Data *string               `json:"data,omitempty"`
	Type TerminalDataEventType `json:"type"`
}

// TerminalDataEventType defines model for TerminalDataEvent.Type.
type TerminalDataEventType string

// TerminalEvent defines model for TerminalEvent.
type TerminalEvent struct {
	Type TerminalEventType `json:"type"`
}

// TerminalEventType defines model for TerminalEvent.Type.
type TerminalEventType string

// TerminalStatusEvent defines model for TerminalStatusEvent.
type TerminalStatusEvent struct {
	// Status The computed status of the agent (derived from container, agent, and head status)
	Status *AgentStatus            `json:"status,omitempty"`
	Type   TerminalStatusEventType `json:"type"`
}

// TerminalStatusEventType defines model for TerminalStatusEvent.Type.
type TerminalStatusEventType string

// UncommittedSummary defines model for UncommittedSummary.
type UncommittedSummary struct {
	// TrackedCount Number of tracked files with staged or unstaged changes
	TrackedCount int `json:"tracked_count"`

	// UntrackedCount Number of untracked (new, never-added) files
	UntrackedCount int `json:"untracked_count"`
}

// KillAgentParams defines parameters for KillAgent.
type KillAgentParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// GetAgentParams defines parameters for GetAgent.
type GetAgentParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// GetAgentCommitsParams defines parameters for GetAgentCommits.
type GetAgentCommitsParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// GetAgentDiffParams defines parameters for GetAgentDiff.
type GetAgentDiffParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`

	// BaseRef Base commit SHA or ref. Defaults to the agent's base branch.
	BaseRef *string `form:"base_ref,omitempty" json:"base_ref,omitempty"`

	// HeadRef Head commit SHA or ref. Defaults to the agent's branch.
	HeadRef *string `form:"head_ref,omitempty" json:"head_ref,omitempty"`

	// IgnoreWhitespace Ignore whitespace changes in the diff
	IgnoreWhitespace *bool `form:"ignore_whitespace,omitempty" json:"ignore_whitespace,omitempty"`

	// IncludeUncommitted Include uncommitted changes in the worktree in the diff
	IncludeUncommitted *bool `form:"include_uncommitted,omitempty" json:"include_uncommitted,omitempty"`
}

// SendAgentInputParams defines parameters for SendAgentInput.
type SendAgentInputParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// MergeAgentParams defines parameters for MergeAgent.
type MergeAgentParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// RestartAgentParams defines parameters for RestartAgent.
type RestartAgentParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// UpdateAgentFromBaseParams defines parameters for UpdateAgentFromBase.
type UpdateAgentFromBaseParams struct {
	// ProjectId Project ID to scope the lookup (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// ProjectId Project ID to scope the agent list (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// SpawnAgentParams defines parameters for SpawnAgent.
type SpawnAgentParams struct {
	// ProjectId Project ID to spawn the agent in (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// GetConfigParams defines parameters for GetConfig.
type GetConfigParams struct {
	// ProjectId Project ID to scope the config (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`

	// Scope Load only a specific scope's raw config instead of the merged config
	Scope *GetConfigParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetConfigParamsScope defines parameters for GetConfig.
type GetConfigParamsScope string

// SaveConfigParams defines parameters for SaveConfig.
type SaveConfigParams struct {
	// ProjectId Project ID to save the config to (defaults to server CWD project)
	ProjectId *string `form:"project_id,omitempty" json:"project_id,omitempty"`

	// Scope Whether to save to the project or user config file (defaults to project)
	Scope *SaveConfigParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// SaveConfigParamsScope defines parameters for SaveConfig.
type SaveConfigParamsScope string

// SendAgentInputJSONRequestBody defines body for SendAgentInput for application/json ContentType.
type SendAgentInputJSONRequestBody = AgentInputRequest

// SpawnAgentJSONRequestBody defines body for SpawnAgent for application/json ContentType.
type SpawnAgentJSONRequestBody = SpawnAgentRequest

// SaveConfigJSONRequestBody defines body for SaveConfig for application/json ContentType.
type SaveConfigJSONRequestBody = ConfigResponse

// AddProjectJSONRequestBody defines body for AddProject for application/json ContentType.
type AddProjectJSONRequestBody = AddProjectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chrome DevTools workspace configuration
	// (GET /.well-known/appspecific/com.chrome.devtools.json)
	GetDevToolsConfig(w http.ResponseWriter, r *http.Request)
	// Kill a Hydra agent by ID
	// (DELETE /api/agent/{id})
	KillAgent(w http.ResponseWriter, r *http.Request, id string, params KillAgentParams)
	// Get a specific Hydra agent by ID
	// (GET /api/agent/{id})
	GetAgent(w http.ResponseWriter, r *http.Request, id string, params GetAgentParams)
	// List commits on an agent's branch (between base branch and agent branch)
	// (GET /api/agent/{id}/commits)
	GetAgentCommits(w http.ResponseWriter, r *http.Request, id string, params GetAgentCommitsParams)
	// Get the diff for an agent's branch
	// (GET /api/agent/{id}/diff)
	GetAgentDiff(w http.ResponseWriter, r *http.Request, id string, params GetAgentDiffParams)
	// Send text input to an agent's terminal stdin
	// (POST /api/agent/{id}/input)
	SendAgentInput(w http.ResponseWriter, r *http.Request, id string, params SendAgentInputParams)
	// Merge a Hydra agent's branch into its base branch and kill it
	// (POST /api/agent/{id}/merge)
	MergeAgent(w http.ResponseWriter, r *http.Request, id string, params MergeAgentParams)
	// Restart a Hydra agent (kill and respawn with the same prompt)
	// (POST /api/agent/{id}/restart)
	RestartAgent(w http.ResponseWriter, r *http.Request, id string, params RestartAgentParams)
	// Update a Hydra agent's branch from its base branch (merge base into head)
	// (POST /api/agent/{id}/update-from-base)
	UpdateAgentFromBase(w http.ResponseWriter, r *http.Request, id string, params UpdateAgentFromBaseParams)
	// List all Hydra agents (heads)
	// (GET /api/agents)
	ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams)
	// Spawn a new Hydra agent
	// (POST /api/agents)
	SpawnAgent(w http.ResponseWriter, r *http.Request, params SpawnAgentParams)
	// Get the merged configuration
	// (GET /api/config)
	GetConfig(w http.ResponseWriter, r *http.Request, params GetConfigParams)
	// Save configuration changes
	// (POST /api/config)
	SaveConfig(w http.ResponseWriter, r *http.Request, params SaveConfigParams)
	// Trigger a server rebuild and restart (dev mode only)
	// (POST /api/dev/restart)
	DevRestart(w http.ResponseWriter, r *http.Request)
	// List all known projects
	// (GET /api/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// Add a new project by folder path
	// (POST /api/projects)
	AddProject(w http.ResponseWriter, r *http.Request)
	// Get system status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDevToolsConfig operation middleware
func (siw *ServerInterfaceWrapper) GetDevToolsConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevToolsConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KillAgent operation middleware
func (siw *ServerInterfaceWrapper) KillAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params KillAgentParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KillAgent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAgentParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentCommits operation middleware
func (siw *ServerInterfaceWrapper) GetAgentCommits(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAgentCommitsParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentCommits(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentDiff operation middleware
func (siw *ServerInterfaceWrapper) GetAgentDiff(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAgentDiffParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	// ------------- Optional query parameter "base_ref" -------------

	err = runtime.BindQueryParameter("form", true, false, "base_ref", r.URL.Query(), &params.BaseRef)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "base_ref", Err: err})
		return
	}

	// ------------- Optional query parameter "head_ref" -------------

	err = runtime.BindQueryParameter("form", true, false, "head_ref", r.URL.Query(), &params.HeadRef)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "head_ref", Err: err})
		return
	}

	// ------------- Optional query parameter "ignore_whitespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "ignore_whitespace", r.URL.Query(), &params.IgnoreWhitespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ignore_whitespace", Err: err})
		return
	}

	// ------------- Optional query parameter "include_uncommitted" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_uncommitted", r.URL.Query(), &params.IncludeUncommitted)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_uncommitted", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentDiff(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendAgentInput operation middleware
func (siw *ServerInterfaceWrapper) SendAgentInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendAgentInputParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendAgentInput(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MergeAgent operation middleware
func (siw *ServerInterfaceWrapper) MergeAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params MergeAgentParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MergeAgent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartAgent operation middleware
func (siw *ServerInterfaceWrapper) RestartAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RestartAgentParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartAgent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentFromBase operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentFromBase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateAgentFromBaseParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentFromBase(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SpawnAgent operation middleware
func (siw *ServerInterfaceWrapper) SpawnAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SpawnAgentParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SpawnAgent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConfigParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveConfig operation middleware
func (siw *ServerInterfaceWrapper) SaveConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SaveConfigParams

	// ------------- Optional query parameter "project_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "project_id", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_id", Err: err})
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", true, false, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveConfig(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DevRestart operation middleware
func (siw *ServerInterfaceWrapper) DevRestart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DevRestart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProject operation middleware
func (siw *ServerInterfaceWrapper) AddProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/.well-known/appspecific/com.chrome.devtools.json", wrapper.GetDevToolsConfig)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/agent/{id}", wrapper.KillAgent)
	m.HandleFunc("GET "+options.BaseURL+"/api/agent/{id}", wrapper.GetAgent)
	m.HandleFunc("GET "+options.BaseURL+"/api/agent/{id}/commits", wrapper.GetAgentCommits)
	m.HandleFunc("GET "+options.BaseURL+"/api/agent/{id}/diff", wrapper.GetAgentDiff)
	m.HandleFunc("POST "+options.BaseURL+"/api/agent/{id}/input", wrapper.SendAgentInput)
	m.HandleFunc("POST "+options.BaseURL+"/api/agent/{id}/merge", wrapper.MergeAgent)
	m.HandleFunc("POST "+options.BaseURL+"/api/agent/{id}/restart", wrapper.RestartAgent)
	m.HandleFunc("POST "+options.BaseURL+"/api/agent/{id}/update-from-base", wrapper.UpdateAgentFromBase)
	m.HandleFunc("GET "+options.BaseURL+"/api/agents", wrapper.ListAgents)
	m.HandleFunc("POST "+options.BaseURL+"/api/agents", wrapper.SpawnAgent)
	m.HandleFunc("GET "+options.BaseURL+"/api/config", wrapper.GetConfig)
	m.HandleFunc("POST "+options.BaseURL+"/api/config", wrapper.SaveConfig)
	m.HandleFunc("POST "+options.BaseURL+"/api/dev/restart", wrapper.DevRestart)
	m.HandleFunc("GET "+options.BaseURL+"/api/projects", wrapper.ListProjects)
	m.HandleFunc("POST "+options.BaseURL+"/api/projects", wrapper.AddProject)
	m.HandleFunc("GET "+options.BaseURL+"/api/status", wrapper.GetStatus)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.CheckHealth)

	return m
}

type GetDevToolsConfigRequestObject struct {
}

type GetDevToolsConfigResponseObject interface {
	VisitGetDevToolsConfigResponse(w http.ResponseWriter) error
}

type GetDevToolsConfig200JSONResponse struct {
	Workspace *struct {
		Root *string `json:"root,omitempty"`
		Uuid *string `json:"uuid,omitempty"`
	} `json:"workspace,omitempty"`
}

func (response GetDevToolsConfig200JSONResponse) VisitGetDevToolsConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevToolsConfig403JSONResponse ErrorResponse

func (response GetDevToolsConfig403JSONResponse) VisitGetDevToolsConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type KillAgentRequestObject struct {
	Id     string `json:"id"`
	Params KillAgentParams
}

type KillAgentResponseObject interface {
	VisitKillAgentResponse(w http.ResponseWriter) error
}

type KillAgent204Response struct {
}

func (response KillAgent204Response) VisitKillAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type KillAgent404JSONResponse ErrorResponse

func (response KillAgent404JSONResponse) VisitKillAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type KillAgent409JSONResponse ErrorResponse

func (response KillAgent409JSONResponse) VisitKillAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type KillAgent500JSONResponse ErrorResponse

func (response KillAgent500JSONResponse) VisitKillAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentRequestObject struct {
	Id     string `json:"id"`
	Params GetAgentParams
}

type GetAgentResponseObject interface {
	VisitGetAgentResponse(w http.ResponseWriter) error
}

type GetAgent200JSONResponse AgentResponse

func (response GetAgent200JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgent404JSONResponse ErrorResponse

func (response GetAgent404JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgent500JSONResponse ErrorResponse

func (response GetAgent500JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentCommitsRequestObject struct {
	Id     string `json:"id"`
	Params GetAgentCommitsParams
}

type GetAgentCommitsResponseObject interface {
	VisitGetAgentCommitsResponse(w http.ResponseWriter) error
}

type GetAgentCommits200JSONResponse []CommitInfo

func (response GetAgentCommits200JSONResponse) VisitGetAgentCommitsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentCommits404JSONResponse ErrorResponse

func (response GetAgentCommits404JSONResponse) VisitGetAgentCommitsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentCommits500JSONResponse ErrorResponse

func (response GetAgentCommits500JSONResponse) VisitGetAgentCommitsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentDiffRequestObject struct {
	Id     string `json:"id"`
	Params GetAgentDiffParams
}

type GetAgentDiffResponseObject interface {
	VisitGetAgentDiffResponse(w http.ResponseWriter) error
}

type GetAgentDiff200JSONResponse DiffResponse

func (response GetAgentDiff200JSONResponse) VisitGetAgentDiffResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentDiff404JSONResponse ErrorResponse

func (response GetAgentDiff404JSONResponse) VisitGetAgentDiffResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentDiff500JSONResponse ErrorResponse

func (response GetAgentDiff500JSONResponse) VisitGetAgentDiffResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SendAgentInputRequestObject struct {
	Id     string `json:"id"`
	Params SendAgentInputParams
	Body   *SendAgentInputJSONRequestBody
}

type SendAgentInputResponseObject interface {
	VisitSendAgentInputResponse(w http.ResponseWriter) error
}

type SendAgentInput200Response struct {
}

func (response SendAgentInput200Response) VisitSendAgentInputResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SendAgentInput404JSONResponse ErrorResponse

func (response SendAgentInput404JSONResponse) VisitSendAgentInputResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendAgentInput500JSONResponse ErrorResponse

func (response SendAgentInput500JSONResponse) VisitSendAgentInputResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MergeAgentRequestObject struct {
	Id     string `json:"id"`
	Params MergeAgentParams
}

type MergeAgentResponseObject interface {
	VisitMergeAgentResponse(w http.ResponseWriter) error
}

type MergeAgent204Response struct {
}

func (response MergeAgent204Response) VisitMergeAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type MergeAgent400JSONResponse ErrorResponse

func (response MergeAgent400JSONResponse) VisitMergeAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type MergeAgent404JSONResponse ErrorResponse

func (response MergeAgent404JSONResponse) VisitMergeAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MergeAgent409JSONResponse MergeConflictError

func (response MergeAgent409JSONResponse) VisitMergeAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MergeAgent500JSONResponse ErrorResponse

func (response MergeAgent500JSONResponse) VisitMergeAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RestartAgentRequestObject struct {
	Id     string `json:"id"`
	Params RestartAgentParams
}

type RestartAgentResponseObject interface {
	VisitRestartAgentResponse(w http.ResponseWriter) error
}

type RestartAgent200JSONResponse AgentResponse

func (response RestartAgent200JSONResponse) VisitRestartAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RestartAgent404JSONResponse ErrorResponse

func (response RestartAgent404JSONResponse) VisitRestartAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RestartAgent409JSONResponse ErrorResponse

func (response RestartAgent409JSONResponse) VisitRestartAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RestartAgent500JSONResponse ErrorResponse

func (response RestartAgent500JSONResponse) VisitRestartAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAgentFromBaseRequestObject struct {
	Id     string `json:"id"`
	Params UpdateAgentFromBaseParams
}

type UpdateAgentFromBaseResponseObject interface {
	VisitUpdateAgentFromBaseResponse(w http.ResponseWriter) error
}

type UpdateAgentFromBase204Response struct {
}

func (response UpdateAgentFromBase204Response) VisitUpdateAgentFromBaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateAgentFromBase404JSONResponse ErrorResponse

func (response UpdateAgentFromBase404JSONResponse) VisitUpdateAgentFromBaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAgentFromBase409JSONResponse MergeConflictError

func (response UpdateAgentFromBase409JSONResponse) VisitUpdateAgentFromBaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAgentFromBase500JSONResponse ErrorResponse

func (response UpdateAgentFromBase500JSONResponse) VisitUpdateAgentFromBaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListAgentsRequestObject struct {
	Params ListAgentsParams
}

type ListAgentsResponseObject interface {
	VisitListAgentsResponse(w http.ResponseWriter) error
}

type ListAgents200JSONResponse []AgentResponse

func (response ListAgents200JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAgents500JSONResponse ErrorResponse

func (response ListAgents500JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SpawnAgentRequestObject struct {
	Params SpawnAgentParams
	Body   *SpawnAgentJSONRequestBody
}

type SpawnAgentResponseObject interface {
	VisitSpawnAgentResponse(w http.ResponseWriter) error
}

type SpawnAgent201JSONResponse AgentResponse

func (response SpawnAgent201JSONResponse) VisitSpawnAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SpawnAgent400JSONResponse ErrorResponse

func (response SpawnAgent400JSONResponse) VisitSpawnAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SpawnAgent500JSONResponse ErrorResponse

func (response SpawnAgent500JSONResponse) VisitSpawnAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetConfigRequestObject struct {
	Params GetConfigParams
}

type GetConfigResponseObject interface {
	VisitGetConfigResponse(w http.ResponseWriter) error
}

type GetConfig200JSONResponse ConfigResponse

func (response GetConfig200JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConfig500JSONResponse ErrorResponse

func (response GetConfig500JSONResponse) VisitGetConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SaveConfigRequestObject struct {
	Params SaveConfigParams
	Body   *SaveConfigJSONRequestBody
}

type SaveConfigResponseObject interface {
	VisitSaveConfigResponse(w http.ResponseWriter) error
}

type SaveConfig200Response struct {
}

func (response SaveConfig200Response) VisitSaveConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SaveConfig500JSONResponse ErrorResponse

func (response SaveConfig500JSONResponse) VisitSaveConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DevRestartRequestObject struct {
}

type DevRestartResponseObject interface {
	VisitDevRestartResponse(w http.ResponseWriter) error
}

type DevRestart200Response struct {
}

func (response DevRestart200Response) VisitDevRestartResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type DevRestart403JSONResponse ErrorResponse

func (response DevRestart403JSONResponse) VisitDevRestartResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListProjectsRequestObject struct {
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse []ProjectInfo

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProjects500JSONResponse ErrorResponse

func (response ListProjects500JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddProjectRequestObject struct {
	Body *AddProjectJSONRequestBody
}

type AddProjectResponseObject interface {
	VisitAddProjectResponse(w http.ResponseWriter) error
}

type AddProject201JSONResponse ProjectInfo

func (response AddProject201JSONResponse) VisitAddProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddProject400JSONResponse ErrorResponse

func (response AddProject400JSONResponse) VisitAddProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddProject500JSONResponse ErrorResponse

func (response AddProject500JSONResponse) VisitAddProjectResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200JSONResponse StatusResponse

func (response GetStatus200JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStatus500JSONResponse ErrorResponse

func (response GetStatus500JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200TextResponse string

func (response CheckHealth200TextResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Chrome DevTools workspace configuration
	// (GET /.well-known/appspecific/com.chrome.devtools.json)
	GetDevToolsConfig(ctx context.Context, request GetDevToolsConfigRequestObject) (GetDevToolsConfigResponseObject, error)
	// Kill a Hydra agent by ID
	// (DELETE /api/agent/{id})
	KillAgent(ctx context.Context, request KillAgentRequestObject) (KillAgentResponseObject, error)
	// Get a specific Hydra agent by ID
	// (GET /api/agent/{id})
	GetAgent(ctx context.Context, request GetAgentRequestObject) (GetAgentResponseObject, error)
	// List commits on an agent's branch (between base branch and agent branch)
	// (GET /api/agent/{id}/commits)
	GetAgentCommits(ctx context.Context, request GetAgentCommitsRequestObject) (GetAgentCommitsResponseObject, error)
	// Get the diff for an agent's branch
	// (GET /api/agent/{id}/diff)
	GetAgentDiff(ctx context.Context, request GetAgentDiffRequestObject) (GetAgentDiffResponseObject, error)
	// Send text input to an agent's terminal stdin
	// (POST /api/agent/{id}/input)
	SendAgentInput(ctx context.Context, request SendAgentInputRequestObject) (SendAgentInputResponseObject, error)
	// Merge a Hydra agent's branch into its base branch and kill it
	// (POST /api/agent/{id}/merge)
	MergeAgent(ctx context.Context, request MergeAgentRequestObject) (MergeAgentResponseObject, error)
	// Restart a Hydra agent (kill and respawn with the same prompt)
	// (POST /api/agent/{id}/restart)
	RestartAgent(ctx context.Context, request RestartAgentRequestObject) (RestartAgentResponseObject, error)
	// Update a Hydra agent's branch from its base branch (merge base into head)
	// (POST /api/agent/{id}/update-from-base)
	UpdateAgentFromBase(ctx context.Context, request UpdateAgentFromBaseRequestObject) (UpdateAgentFromBaseResponseObject, error)
	// List all Hydra agents (heads)
	// (GET /api/agents)
	ListAgents(ctx context.Context, request ListAgentsRequestObject) (ListAgentsResponseObject, error)
	// Spawn a new Hydra agent
	// (POST /api/agents)
	SpawnAgent(ctx context.Context, request SpawnAgentRequestObject) (SpawnAgentResponseObject, error)
	// Get the merged configuration
	// (GET /api/config)
	GetConfig(ctx context.Context, request GetConfigRequestObject) (GetConfigResponseObject, error)
	// Save configuration changes
	// (POST /api/config)
	SaveConfig(ctx context.Context, request SaveConfigRequestObject) (SaveConfigResponseObject, error)
	// Trigger a server rebuild and restart (dev mode only)
	// (POST /api/dev/restart)
	DevRestart(ctx context.Context, request DevRestartRequestObject) (DevRestartResponseObject, error)
	// List all known projects
	// (GET /api/projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// Add a new project by folder path
	// (POST /api/projects)
	AddProject(ctx context.Context, request AddProjectRequestObject) (AddProjectResponseObject, error)
	// Get system status
	// (GET /api/status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// Health check
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDevToolsConfig operation middleware
func (sh *strictHandler) GetDevToolsConfig(w http.ResponseWriter, r *http.Request) {
	var request GetDevToolsConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevToolsConfig(ctx, request.(GetDevToolsConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevToolsConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevToolsConfigResponseObject); ok {
		if err := validResponse.VisitGetDevToolsConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// KillAgent operation middleware
func (sh *strictHandler) KillAgent(w http.ResponseWriter, r *http.Request, id string, params KillAgentParams) {
	var request KillAgentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.KillAgent(ctx, request.(KillAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "KillAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(KillAgentResponseObject); ok {
		if err := validResponse.VisitKillAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgent operation middleware
func (sh *strictHandler) GetAgent(w http.ResponseWriter, r *http.Request, id string, params GetAgentParams) {
	var request GetAgentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgent(ctx, request.(GetAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentResponseObject); ok {
		if err := validResponse.VisitGetAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentCommits operation middleware
func (sh *strictHandler) GetAgentCommits(w http.ResponseWriter, r *http.Request, id string, params GetAgentCommitsParams) {
	var request GetAgentCommitsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentCommits(ctx, request.(GetAgentCommitsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentCommits")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentCommitsResponseObject); ok {
		if err := validResponse.VisitGetAgentCommitsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentDiff operation middleware
func (sh *strictHandler) GetAgentDiff(w http.ResponseWriter, r *http.Request, id string, params GetAgentDiffParams) {
	var request GetAgentDiffRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentDiff(ctx, request.(GetAgentDiffRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentDiff")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentDiffResponseObject); ok {
		if err := validResponse.VisitGetAgentDiffResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendAgentInput operation middleware
func (sh *strictHandler) SendAgentInput(w http.ResponseWriter, r *http.Request, id string, params SendAgentInputParams) {
	var request SendAgentInputRequestObject

	request.Id = id
	request.Params = params

	var body SendAgentInputJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendAgentInput(ctx, request.(SendAgentInputRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendAgentInput")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendAgentInputResponseObject); ok {
		if err := validResponse.VisitSendAgentInputResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MergeAgent operation middleware
func (sh *strictHandler) MergeAgent(w http.ResponseWriter, r *http.Request, id string, params MergeAgentParams) {
	var request MergeAgentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MergeAgent(ctx, request.(MergeAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MergeAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MergeAgentResponseObject); ok {
		if err := validResponse.VisitMergeAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestartAgent operation middleware
func (sh *strictHandler) RestartAgent(w http.ResponseWriter, r *http.Request, id string, params RestartAgentParams) {
	var request RestartAgentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestartAgent(ctx, request.(RestartAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestartAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestartAgentResponseObject); ok {
		if err := validResponse.VisitRestartAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAgentFromBase operation middleware
func (sh *strictHandler) UpdateAgentFromBase(w http.ResponseWriter, r *http.Request, id string, params UpdateAgentFromBaseParams) {
	var request UpdateAgentFromBaseRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAgentFromBase(ctx, request.(UpdateAgentFromBaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAgentFromBase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAgentFromBaseResponseObject); ok {
		if err := validResponse.VisitUpdateAgentFromBaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAgents operation middleware
func (sh *strictHandler) ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams) {
	var request ListAgentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgents(ctx, request.(ListAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAgentsResponseObject); ok {
		if err := validResponse.VisitListAgentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SpawnAgent operation middleware
func (sh *strictHandler) SpawnAgent(w http.ResponseWriter, r *http.Request, params SpawnAgentParams) {
	var request SpawnAgentRequestObject

	request.Params = params

	var body SpawnAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SpawnAgent(ctx, request.(SpawnAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SpawnAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SpawnAgentResponseObject); ok {
		if err := validResponse.VisitSpawnAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConfig operation middleware
func (sh *strictHandler) GetConfig(w http.ResponseWriter, r *http.Request, params GetConfigParams) {
	var request GetConfigRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConfig(ctx, request.(GetConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConfigResponseObject); ok {
		if err := validResponse.VisitGetConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveConfig operation middleware
func (sh *strictHandler) SaveConfig(w http.ResponseWriter, r *http.Request, params SaveConfigParams) {
	var request SaveConfigRequestObject

	request.Params = params

	var body SaveConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SaveConfig(ctx, request.(SaveConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SaveConfigResponseObject); ok {
		if err := validResponse.VisitSaveConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DevRestart operation middleware
func (sh *strictHandler) DevRestart(w http.ResponseWriter, r *http.Request) {
	var request DevRestartRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DevRestart(ctx, request.(DevRestartRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DevRestart")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DevRestartResponseObject); ok {
		if err := validResponse.VisitDevRestartResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(w http.ResponseWriter, r *http.Request) {
	var request ListProjectsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx, request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		if err := validResponse.VisitListProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddProject operation middleware
func (sh *strictHandler) AddProject(w http.ResponseWriter, r *http.Request) {
	var request AddProjectRequestObject

	var body AddProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddProject(ctx, request.(AddProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddProjectResponseObject); ok {
		if err := validResponse.VisitAddProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
