// Package agenthostapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package agenthostapi

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/trolleyman/hydra/internal/api"
	externalRef1 "github.com/trolleyman/hydra/internal/policyapi"
)

// Defines values for ApprovalRequestFrameKind.
const (
	FilesystemRead  ApprovalRequestFrameKind = "filesystem_read"
	FilesystemWrite ApprovalRequestFrameKind = "filesystem_write"
	Git             ApprovalRequestFrameKind = "git"
	Integration     ApprovalRequestFrameKind = "integration"
	Mcp             ApprovalRequestFrameKind = "mcp"
	McpTool         ApprovalRequestFrameKind = "mcp_tool"
	Network         ApprovalRequestFrameKind = "network"
)

// Defines values for ApprovalRequestFrameType.
const (
	ApprovalRequest ApprovalRequestFrameType = "approval_request"
)

// Defines values for ApprovalResponseCommandDecision.
const (
	Allow ApprovalResponseCommandDecision = "allow"
	Deny  ApprovalResponseCommandDecision = "deny"
)

// Defines values for ApprovalResponseCommandScope.
const (
	Chat      ApprovalResponseCommandScope = "chat"
	Once      ApprovalResponseCommandScope = "once"
	Profile   ApprovalResponseCommandScope = "profile"
	Workspace ApprovalResponseCommandScope = "workspace"
)

// Defines values for ApprovalResponseCommandType.
const (
	ApprovalResponse ApprovalResponseCommandType = "approval_response"
)

// Defines values for ChatEventFrameType.
const (
	ChatEvent ChatEventFrameType = "chat_event"
)

// Defines values for ChatHistoryFrameType.
const (
	ChatHistory ChatHistoryFrameType = "chat_history"
)

// Defines values for ControlResponseCommandType.
const (
	ControlResponse ControlResponseCommandType = "control_response"
)

// Defines values for HelloFrameType.
const (
	Hello HelloFrameType = "hello"
)

// Defines values for HostErrorFrameType.
const (
	HostError HostErrorFrameType = "host_error"
)

// Defines values for InitializeCommandType.
const (
	Initialize InitializeCommandType = "initialize"
)

// Defines values for InterruptCommandType.
const (
	InterruptCommandTypeInterrupt InterruptCommandType = "interrupt"
)

// Defines values for LoadEventsBeforeCommandType.
const (
	LoadEventsBefore LoadEventsBeforeCommandType = "load_events_before"
)

// Defines values for LoadSubagentCommandType.
const (
	LoadSubagent LoadSubagentCommandType = "load_subagent"
)

// Defines values for OperationResultFrameType.
const (
	OperationResult OperationResultFrameType = "operation_result"
)

// Defines values for ReadyFrameType.
const (
	Ready ReadyFrameType = "ready"
)

// Defines values for ReplayDoneFrameType.
const (
	ReplayDone ReplayDoneFrameType = "replay_done"
)

// Defines values for SetModelCommandType.
const (
	SetModel SetModelCommandType = "set_model"
)

// Defines values for ShutdownCommandType.
const (
	Shutdown ShutdownCommandType = "shutdown"
)

// Defines values for StateSnapshotFrameType.
const (
	StateSnapshot StateSnapshotFrameType = "state_snapshot"
)

// Defines values for SubagentEventsFrameType.
const (
	SubagentEvents SubagentEventsFrameType = "subagent_events"
)

// Defines values for UpdatePolicyCommandBehavior.
const (
	UpdatePolicyCommandBehaviorInterrupt UpdatePolicyCommandBehavior = "interrupt"
	UpdatePolicyCommandBehaviorNextTurn  UpdatePolicyCommandBehavior = "next_turn"
)

// Defines values for UpdatePolicyCommandType.
const (
	UpdatePolicy UpdatePolicyCommandType = "update_policy"
)

// Defines values for UserMessageCommandType.
const (
	UserMessage UserMessageCommandType = "user_message"
)

// ApprovalRequestFrame defines model for ApprovalRequestFrame.
type ApprovalRequestFrame struct {
	CanonicalTarget string                   `json:"canonical_target,omitempty"`
	Kind            ApprovalRequestFrameKind `json:"kind"`
	Reason          string                   `json:"reason,omitempty"`
	RequestId       string                   `json:"request_id"`
	Summary         string                   `json:"summary"`
	Target          string                   `json:"target"`
	Type            ApprovalRequestFrameType `json:"type"`
}

// ApprovalRequestFrameKind defines model for ApprovalRequestFrame.Kind.
type ApprovalRequestFrameKind string

// ApprovalRequestFrameType defines model for ApprovalRequestFrame.Type.
type ApprovalRequestFrameType string

// ApprovalResponseCommand defines model for ApprovalResponseCommand.
type ApprovalResponseCommand struct {
	Decision  ApprovalResponseCommandDecision `json:"decision"`
	RequestId string                          `json:"request_id"`
	Scope     ApprovalResponseCommandScope    `json:"scope"`
	Type      ApprovalResponseCommandType     `json:"type"`
}

// ApprovalResponseCommandDecision defines model for ApprovalResponseCommand.Decision.
type ApprovalResponseCommandDecision string

// ApprovalResponseCommandScope defines model for ApprovalResponseCommand.Scope.
type ApprovalResponseCommandScope string

// ApprovalResponseCommandType defines model for ApprovalResponseCommand.Type.
type ApprovalResponseCommandType string

// ChatEventFrame defines model for ChatEventFrame.
type ChatEventFrame struct {
	// Event One durable normalized event. `seq` is per-head, monotonic, and the sole wire and cursor identity - provider object ids stay inside `payload`.
	Event externalRef0.ChatEvent `json:"event"`
	Type  ChatEventFrameType     `json:"type"`
}

// ChatEventFrameType defines model for ChatEventFrame.Type.
type ChatEventFrameType string

// ChatHistoryFrame defines model for ChatHistoryFrame.
type ChatHistoryFrame struct {
	Done       bool                     `json:"done"`
	Events     []externalRef0.ChatEvent `json:"events"`
	NextCursor string                   `json:"next_cursor,omitempty"`
	RequestId  string                   `json:"request_id"`
	Type       ChatHistoryFrameType     `json:"type"`
}

// ChatHistoryFrameType defines model for ChatHistoryFrame.Type.
type ChatHistoryFrameType string

// ControlResponseCommand defines model for ControlResponseCommand.
type ControlResponseCommand struct {
	RequestId string                     `json:"request_id"`
	Response  map[string]interface{}     `json:"response"`
	Type      ControlResponseCommandType `json:"type"`
}

// ControlResponseCommandType defines model for ControlResponseCommand.Type.
type ControlResponseCommandType string

// HelloFrame defines model for HelloFrame.
type HelloFrame struct {
	HostVersion     string         `json:"host_version"`
	ProtocolVersion int            `json:"protocol_version"`
	Type            HelloFrameType `json:"type"`
}

// HelloFrameType defines model for HelloFrame.Type.
type HelloFrameType string

// HostCommand One newline-delimited command sent to hydra-agent-host stdin.
type HostCommand struct {
	union json.RawMessage
}

// HostErrorFrame defines model for HostErrorFrame.
type HostErrorFrame struct {
	Code      string             `json:"code"`
	Fatal     bool               `json:"fatal"`
	Message   string             `json:"message"`
	RequestId string             `json:"request_id,omitempty"`
	Type      HostErrorFrameType `json:"type"`
}

// HostErrorFrameType defines model for HostErrorFrame.Type.
type HostErrorFrameType string

// HostFrame One newline-delimited frame emitted by hydra-agent-host stdout.
type HostFrame struct {
	union json.RawMessage
}

// InitializeCommand defines model for InitializeCommand.
type InitializeCommand struct {
	ConversationDir string `json:"conversation_dir"`

	// Policy Resolved and canonical policy accepted by the native host.
	Policy          externalRef1.EffectivePolicy `json:"policy"`
	ProtocolVersion int                          `json:"protocol_version"`

	// ProviderExecutable Executable name or absolute path selected by the workspace extension.
	ProviderExecutable string                `json:"provider_executable,omitempty"`
	ResumeSessionId    string                `json:"resume_session_id,omitempty"`
	Type               InitializeCommandType `json:"type"`
	Workspace          string                `json:"workspace"`
}

// InitializeCommandType defines model for InitializeCommand.Type.
type InitializeCommandType string

// InterruptCommand defines model for InterruptCommand.
type InterruptCommand struct {
	RequestId string               `json:"request_id"`
	Type      InterruptCommandType `json:"type"`
}

// InterruptCommandType defines model for InterruptCommand.Type.
type InterruptCommandType string

// LoadEventsBeforeCommand defines model for LoadEventsBeforeCommand.
type LoadEventsBeforeCommand struct {
	Cursor    string                      `json:"cursor,omitempty"`
	Limit     int                         `json:"limit"`
	RequestId string                      `json:"request_id"`
	Type      LoadEventsBeforeCommandType `json:"type"`
}

// LoadEventsBeforeCommandType defines model for LoadEventsBeforeCommand.Type.
type LoadEventsBeforeCommandType string

// LoadSubagentCommand defines model for LoadSubagentCommand.
type LoadSubagentCommand struct {
	AgentId   string                  `json:"agent_id"`
	RequestId string                  `json:"request_id"`
	Type      LoadSubagentCommandType `json:"type"`
}

// LoadSubagentCommandType defines model for LoadSubagentCommand.Type.
type LoadSubagentCommandType string

// OperationResultFrame defines model for OperationResultFrame.
type OperationResultFrame struct {
	Error     string                   `json:"error,omitempty"`
	Ok        bool                     `json:"ok"`
	RequestId string                   `json:"request_id"`
	Type      OperationResultFrameType `json:"type"`
}

// OperationResultFrameType defines model for OperationResultFrame.Type.
type OperationResultFrameType string

// ReadyFrame defines model for ReadyFrame.
type ReadyFrame struct {
	Provider  externalRef1.ProviderKind `json:"provider"`
	SessionId string                    `json:"session_id,omitempty"`
	Type      ReadyFrameType            `json:"type"`
}

// ReadyFrameType defines model for ReadyFrame.Type.
type ReadyFrameType string

// ReplayDoneFrame defines model for ReplayDoneFrame.
type ReplayDoneFrame struct {
	Type ReplayDoneFrameType `json:"type"`
}

// ReplayDoneFrameType defines model for ReplayDoneFrame.Type.
type ReplayDoneFrameType string

// SetModelCommand defines model for SetModelCommand.
type SetModelCommand struct {
	Model     string              `json:"model"`
	RequestId string              `json:"request_id"`
	Type      SetModelCommandType `json:"type"`
}

// SetModelCommandType defines model for SetModelCommand.Type.
type SetModelCommandType string

// ShutdownCommand defines model for ShutdownCommand.
type ShutdownCommand struct {
	Type ShutdownCommandType `json:"type"`
}

// ShutdownCommandType defines model for ShutdownCommand.Type.
type ShutdownCommandType string

// StateSnapshotFrame defines model for StateSnapshotFrame.
type StateSnapshotFrame struct {
	// Projection Bounded current state, folded from the event log and checkpointed with the sequence it was folded through. Complete messages, tool output and sub-agent transcripts stay in the paged log, so this does not grow with the conversation.
	Projection externalRef0.ChatProjection `json:"projection"`
	Type       StateSnapshotFrameType      `json:"type"`
}

// StateSnapshotFrameType defines model for StateSnapshotFrame.Type.
type StateSnapshotFrameType string

// SubagentEventsFrame defines model for SubagentEventsFrame.
type SubagentEventsFrame struct {
	AgentId   string                   `json:"agent_id"`
	Events    []externalRef0.ChatEvent `json:"events"`
	RequestId string                   `json:"request_id"`
	Type      SubagentEventsFrameType  `json:"type"`
}

// SubagentEventsFrameType defines model for SubagentEventsFrame.Type.
type SubagentEventsFrameType string

// UpdatePolicyCommand defines model for UpdatePolicyCommand.
type UpdatePolicyCommand struct {
	Behavior UpdatePolicyCommandBehavior `json:"behavior"`

	// Policy Resolved and canonical policy accepted by the native host.
	Policy    externalRef1.EffectivePolicy `json:"policy"`
	RequestId string                       `json:"request_id"`
	Type      UpdatePolicyCommandType      `json:"type"`
}

// UpdatePolicyCommandBehavior defines model for UpdatePolicyCommand.Behavior.
type UpdatePolicyCommandBehavior string

// UpdatePolicyCommandType defines model for UpdatePolicyCommand.Type.
type UpdatePolicyCommandType string

// UserMessageCommand defines model for UserMessageCommand.
type UserMessageCommand struct {
	Content   []map[string]interface{} `json:"content"`
	Id        string                   `json:"id"`
	RequestId string                   `json:"request_id"`
	Type      UserMessageCommandType   `json:"type"`
}

// UserMessageCommandType defines model for UserMessageCommand.Type.
type UserMessageCommandType string

// AsInitializeCommand returns the union data inside the HostCommand as a InitializeCommand
func (t HostCommand) AsInitializeCommand() (InitializeCommand, error) {
	var body InitializeCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInitializeCommand overwrites any union data inside the HostCommand as the provided InitializeCommand
func (t *HostCommand) FromInitializeCommand(v InitializeCommand) error {
	v.Type = "initialize"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInitializeCommand performs a merge with any union data inside the HostCommand, using the provided InitializeCommand
func (t *HostCommand) MergeInitializeCommand(v InitializeCommand) error {
	v.Type = "initialize"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserMessageCommand returns the union data inside the HostCommand as a UserMessageCommand
func (t HostCommand) AsUserMessageCommand() (UserMessageCommand, error) {
	var body UserMessageCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserMessageCommand overwrites any union data inside the HostCommand as the provided UserMessageCommand
func (t *HostCommand) FromUserMessageCommand(v UserMessageCommand) error {
	v.Type = "user_message"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserMessageCommand performs a merge with any union data inside the HostCommand, using the provided UserMessageCommand
func (t *HostCommand) MergeUserMessageCommand(v UserMessageCommand) error {
	v.Type = "user_message"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInterruptCommand returns the union data inside the HostCommand as a InterruptCommand
func (t HostCommand) AsInterruptCommand() (InterruptCommand, error) {
	var body InterruptCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInterruptCommand overwrites any union data inside the HostCommand as the provided InterruptCommand
func (t *HostCommand) FromInterruptCommand(v InterruptCommand) error {
	v.Type = "interrupt"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInterruptCommand performs a merge with any union data inside the HostCommand, using the provided InterruptCommand
func (t *HostCommand) MergeInterruptCommand(v InterruptCommand) error {
	v.Type = "interrupt"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetModelCommand returns the union data inside the HostCommand as a SetModelCommand
func (t HostCommand) AsSetModelCommand() (SetModelCommand, error) {
	var body SetModelCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetModelCommand overwrites any union data inside the HostCommand as the provided SetModelCommand
func (t *HostCommand) FromSetModelCommand(v SetModelCommand) error {
	v.Type = "set_model"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetModelCommand performs a merge with any union data inside the HostCommand, using the provided SetModelCommand
func (t *HostCommand) MergeSetModelCommand(v SetModelCommand) error {
	v.Type = "set_model"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsControlResponseCommand returns the union data inside the HostCommand as a ControlResponseCommand
func (t HostCommand) AsControlResponseCommand() (ControlResponseCommand, error) {
	var body ControlResponseCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromControlResponseCommand overwrites any union data inside the HostCommand as the provided ControlResponseCommand
func (t *HostCommand) FromControlResponseCommand(v ControlResponseCommand) error {
	v.Type = "control_response"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeControlResponseCommand performs a merge with any union data inside the HostCommand, using the provided ControlResponseCommand
func (t *HostCommand) MergeControlResponseCommand(v ControlResponseCommand) error {
	v.Type = "control_response"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApprovalResponseCommand returns the union data inside the HostCommand as a ApprovalResponseCommand
func (t HostCommand) AsApprovalResponseCommand() (ApprovalResponseCommand, error) {
	var body ApprovalResponseCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApprovalResponseCommand overwrites any union data inside the HostCommand as the provided ApprovalResponseCommand
func (t *HostCommand) FromApprovalResponseCommand(v ApprovalResponseCommand) error {
	v.Type = "approval_response"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApprovalResponseCommand performs a merge with any union data inside the HostCommand, using the provided ApprovalResponseCommand
func (t *HostCommand) MergeApprovalResponseCommand(v ApprovalResponseCommand) error {
	v.Type = "approval_response"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLoadEventsBeforeCommand returns the union data inside the HostCommand as a LoadEventsBeforeCommand
func (t HostCommand) AsLoadEventsBeforeCommand() (LoadEventsBeforeCommand, error) {
	var body LoadEventsBeforeCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoadEventsBeforeCommand overwrites any union data inside the HostCommand as the provided LoadEventsBeforeCommand
func (t *HostCommand) FromLoadEventsBeforeCommand(v LoadEventsBeforeCommand) error {
	v.Type = "load_events_before"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLoadEventsBeforeCommand performs a merge with any union data inside the HostCommand, using the provided LoadEventsBeforeCommand
func (t *HostCommand) MergeLoadEventsBeforeCommand(v LoadEventsBeforeCommand) error {
	v.Type = "load_events_before"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLoadSubagentCommand returns the union data inside the HostCommand as a LoadSubagentCommand
func (t HostCommand) AsLoadSubagentCommand() (LoadSubagentCommand, error) {
	var body LoadSubagentCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLoadSubagentCommand overwrites any union data inside the HostCommand as the provided LoadSubagentCommand
func (t *HostCommand) FromLoadSubagentCommand(v LoadSubagentCommand) error {
	v.Type = "load_subagent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLoadSubagentCommand performs a merge with any union data inside the HostCommand, using the provided LoadSubagentCommand
func (t *HostCommand) MergeLoadSubagentCommand(v LoadSubagentCommand) error {
	v.Type = "load_subagent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUpdatePolicyCommand returns the union data inside the HostCommand as a UpdatePolicyCommand
func (t HostCommand) AsUpdatePolicyCommand() (UpdatePolicyCommand, error) {
	var body UpdatePolicyCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUpdatePolicyCommand overwrites any union data inside the HostCommand as the provided UpdatePolicyCommand
func (t *HostCommand) FromUpdatePolicyCommand(v UpdatePolicyCommand) error {
	v.Type = "update_policy"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUpdatePolicyCommand performs a merge with any union data inside the HostCommand, using the provided UpdatePolicyCommand
func (t *HostCommand) MergeUpdatePolicyCommand(v UpdatePolicyCommand) error {
	v.Type = "update_policy"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsShutdownCommand returns the union data inside the HostCommand as a ShutdownCommand
func (t HostCommand) AsShutdownCommand() (ShutdownCommand, error) {
	var body ShutdownCommand
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromShutdownCommand overwrites any union data inside the HostCommand as the provided ShutdownCommand
func (t *HostCommand) FromShutdownCommand(v ShutdownCommand) error {
	v.Type = "shutdown"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeShutdownCommand performs a merge with any union data inside the HostCommand, using the provided ShutdownCommand
func (t *HostCommand) MergeShutdownCommand(v ShutdownCommand) error {
	v.Type = "shutdown"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t HostCommand) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t HostCommand) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "approval_response":
		return t.AsApprovalResponseCommand()
	case "control_response":
		return t.AsControlResponseCommand()
	case "initialize":
		return t.AsInitializeCommand()
	case "interrupt":
		return t.AsInterruptCommand()
	case "load_events_before":
		return t.AsLoadEventsBeforeCommand()
	case "load_subagent":
		return t.AsLoadSubagentCommand()
	case "set_model":
		return t.AsSetModelCommand()
	case "shutdown":
		return t.AsShutdownCommand()
	case "update_policy":
		return t.AsUpdatePolicyCommand()
	case "user_message":
		return t.AsUserMessageCommand()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t HostCommand) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *HostCommand) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsHelloFrame returns the union data inside the HostFrame as a HelloFrame
func (t HostFrame) AsHelloFrame() (HelloFrame, error) {
	var body HelloFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelloFrame overwrites any union data inside the HostFrame as the provided HelloFrame
func (t *HostFrame) FromHelloFrame(v HelloFrame) error {
	v.Type = "hello"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelloFrame performs a merge with any union data inside the HostFrame, using the provided HelloFrame
func (t *HostFrame) MergeHelloFrame(v HelloFrame) error {
	v.Type = "hello"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReadyFrame returns the union data inside the HostFrame as a ReadyFrame
func (t HostFrame) AsReadyFrame() (ReadyFrame, error) {
	var body ReadyFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReadyFrame overwrites any union data inside the HostFrame as the provided ReadyFrame
func (t *HostFrame) FromReadyFrame(v ReadyFrame) error {
	v.Type = "ready"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReadyFrame performs a merge with any union data inside the HostFrame, using the provided ReadyFrame
func (t *HostFrame) MergeReadyFrame(v ReadyFrame) error {
	v.Type = "ready"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStateSnapshotFrame returns the union data inside the HostFrame as a StateSnapshotFrame
func (t HostFrame) AsStateSnapshotFrame() (StateSnapshotFrame, error) {
	var body StateSnapshotFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStateSnapshotFrame overwrites any union data inside the HostFrame as the provided StateSnapshotFrame
func (t *HostFrame) FromStateSnapshotFrame(v StateSnapshotFrame) error {
	v.Type = "state_snapshot"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStateSnapshotFrame performs a merge with any union data inside the HostFrame, using the provided StateSnapshotFrame
func (t *HostFrame) MergeStateSnapshotFrame(v StateSnapshotFrame) error {
	v.Type = "state_snapshot"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatHistoryFrame returns the union data inside the HostFrame as a ChatHistoryFrame
func (t HostFrame) AsChatHistoryFrame() (ChatHistoryFrame, error) {
	var body ChatHistoryFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatHistoryFrame overwrites any union data inside the HostFrame as the provided ChatHistoryFrame
func (t *HostFrame) FromChatHistoryFrame(v ChatHistoryFrame) error {
	v.Type = "chat_history"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatHistoryFrame performs a merge with any union data inside the HostFrame, using the provided ChatHistoryFrame
func (t *HostFrame) MergeChatHistoryFrame(v ChatHistoryFrame) error {
	v.Type = "chat_history"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatEventFrame returns the union data inside the HostFrame as a ChatEventFrame
func (t HostFrame) AsChatEventFrame() (ChatEventFrame, error) {
	var body ChatEventFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatEventFrame overwrites any union data inside the HostFrame as the provided ChatEventFrame
func (t *HostFrame) FromChatEventFrame(v ChatEventFrame) error {
	v.Type = "chat_event"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatEventFrame performs a merge with any union data inside the HostFrame, using the provided ChatEventFrame
func (t *HostFrame) MergeChatEventFrame(v ChatEventFrame) error {
	v.Type = "chat_event"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubagentEventsFrame returns the union data inside the HostFrame as a SubagentEventsFrame
func (t HostFrame) AsSubagentEventsFrame() (SubagentEventsFrame, error) {
	var body SubagentEventsFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubagentEventsFrame overwrites any union data inside the HostFrame as the provided SubagentEventsFrame
func (t *HostFrame) FromSubagentEventsFrame(v SubagentEventsFrame) error {
	v.Type = "subagent_events"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubagentEventsFrame performs a merge with any union data inside the HostFrame, using the provided SubagentEventsFrame
func (t *HostFrame) MergeSubagentEventsFrame(v SubagentEventsFrame) error {
	v.Type = "subagent_events"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReplayDoneFrame returns the union data inside the HostFrame as a ReplayDoneFrame
func (t HostFrame) AsReplayDoneFrame() (ReplayDoneFrame, error) {
	var body ReplayDoneFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReplayDoneFrame overwrites any union data inside the HostFrame as the provided ReplayDoneFrame
func (t *HostFrame) FromReplayDoneFrame(v ReplayDoneFrame) error {
	v.Type = "replay_done"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReplayDoneFrame performs a merge with any union data inside the HostFrame, using the provided ReplayDoneFrame
func (t *HostFrame) MergeReplayDoneFrame(v ReplayDoneFrame) error {
	v.Type = "replay_done"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApprovalRequestFrame returns the union data inside the HostFrame as a ApprovalRequestFrame
func (t HostFrame) AsApprovalRequestFrame() (ApprovalRequestFrame, error) {
	var body ApprovalRequestFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApprovalRequestFrame overwrites any union data inside the HostFrame as the provided ApprovalRequestFrame
func (t *HostFrame) FromApprovalRequestFrame(v ApprovalRequestFrame) error {
	v.Type = "approval_request"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApprovalRequestFrame performs a merge with any union data inside the HostFrame, using the provided ApprovalRequestFrame
func (t *HostFrame) MergeApprovalRequestFrame(v ApprovalRequestFrame) error {
	v.Type = "approval_request"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOperationResultFrame returns the union data inside the HostFrame as a OperationResultFrame
func (t HostFrame) AsOperationResultFrame() (OperationResultFrame, error) {
	var body OperationResultFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOperationResultFrame overwrites any union data inside the HostFrame as the provided OperationResultFrame
func (t *HostFrame) FromOperationResultFrame(v OperationResultFrame) error {
	v.Type = "operation_result"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOperationResultFrame performs a merge with any union data inside the HostFrame, using the provided OperationResultFrame
func (t *HostFrame) MergeOperationResultFrame(v OperationResultFrame) error {
	v.Type = "operation_result"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHostErrorFrame returns the union data inside the HostFrame as a HostErrorFrame
func (t HostFrame) AsHostErrorFrame() (HostErrorFrame, error) {
	var body HostErrorFrame
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHostErrorFrame overwrites any union data inside the HostFrame as the provided HostErrorFrame
func (t *HostFrame) FromHostErrorFrame(v HostErrorFrame) error {
	v.Type = "host_error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHostErrorFrame performs a merge with any union data inside the HostFrame, using the provided HostErrorFrame
func (t *HostFrame) MergeHostErrorFrame(v HostErrorFrame) error {
	v.Type = "host_error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t HostFrame) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t HostFrame) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "approval_request":
		return t.AsApprovalRequestFrame()
	case "chat_event":
		return t.AsChatEventFrame()
	case "chat_history":
		return t.AsChatHistoryFrame()
	case "hello":
		return t.AsHelloFrame()
	case "host_error":
		return t.AsHostErrorFrame()
	case "operation_result":
		return t.AsOperationResultFrame()
	case "ready":
		return t.AsReadyFrame()
	case "replay_done":
		return t.AsReplayDoneFrame()
	case "state_snapshot":
		return t.AsStateSnapshotFrame()
	case "subagent_events":
		return t.AsSubagentEventsFrame()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t HostFrame) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *HostFrame) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
