// Package policyapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package policyapi

// Defines values for GitIsolation.
const (
	GitOff      GitIsolation = "off"
	GitReadOnly GitIsolation = "readonly"
)

// Defines values for MCPServerPolicyTransport.
const (
	MCPLocal  MCPServerPolicyTransport = "local"
	MCPRemote MCPServerPolicyTransport = "remote"
)

// Defines values for NetworkMode.
const (
	NetworkAdvisory     NetworkMode = "advisory"
	NetworkHard         NetworkMode = "hard"
	NetworkOff          NetworkMode = "off"
	NetworkUnrestricted NetworkMode = "unrestricted"
)

// Defines values for PolicyDecision.
const (
	PolicyAllow PolicyDecision = "allow"
	PolicyAsk   PolicyDecision = "ask"
	PolicyDeny  PolicyDecision = "deny"
)

// Defines values for ProviderKind.
const (
	ProviderClaude ProviderKind = "claude"
	ProviderCodex  ProviderKind = "codex"
)

// AuthoredFilesystemPolicy defines model for AuthoredFilesystemPolicy.
type AuthoredFilesystemPolicy struct {
	CopyOnWrite *[]string `json:"copy_on_write,omitempty"`
	Masked      *[]string `json:"masked,omitempty"`
	Readable    *[]string `json:"readable,omitempty"`
	Writable    *[]string `json:"writable,omitempty"`
}

// AuthoredNetworkPolicy defines model for AuthoredNetworkPolicy.
type AuthoredNetworkPolicy struct {
	AllowedHosts *[]string `json:"allowed_hosts,omitempty"`
	BlockedHosts *[]string `json:"blocked_hosts,omitempty"`

	// Mode Enforcement posture for sandboxed outbound connections.
	Mode *NetworkMode `json:"mode,omitempty"`
}

// CoreToolPolicy defines model for CoreToolPolicy.
type CoreToolPolicy struct {
	// Bash Whether a capability proceeds, asks the user, or is refused.
	Bash *PolicyDecision `json:"bash,omitempty"`

	// Edit Whether a capability proceeds, asks the user, or is refused.
	Edit *PolicyDecision `json:"edit,omitempty"`

	// Fetch Whether a capability proceeds, asks the user, or is refused.
	Fetch *PolicyDecision `json:"fetch,omitempty"`

	// Read Whether a capability proceeds, asks the user, or is refused.
	Read *PolicyDecision `json:"read,omitempty"`

	// Search Whether a capability proceeds, asks the user, or is refused.
	Search *PolicyDecision `json:"search,omitempty"`
}

// EffectiveFilesystemPolicy defines model for EffectiveFilesystemPolicy.
type EffectiveFilesystemPolicy struct {
	// CopyOnWrite Canonical absolute paths with per-conversation write layers.
	CopyOnWrite []string `json:"copy_on_write"`

	// Masked Canonical absolute paths hidden after all grants are applied.
	Masked []string `json:"masked"`

	// Readable Canonical absolute paths exposed read-only.
	Readable []string `json:"readable"`

	// Writable Canonical absolute paths exposed read-write.
	Writable []string `json:"writable"`
}

// EffectiveNetworkPolicy defines model for EffectiveNetworkPolicy.
type EffectiveNetworkPolicy struct {
	AllowedHosts []string `json:"allowed_hosts"`
	BlockedHosts []string `json:"blocked_hosts"`

	// Mode Enforcement posture for sandboxed outbound connections.
	Mode NetworkMode `json:"mode"`
}

// EffectivePolicy Resolved and canonical policy accepted by the native host.
type EffectivePolicy struct {
	// Effort Provider-specific reasoning effort.
	Effort     string                    `json:"effort,omitempty"`
	Filesystem EffectiveFilesystemPolicy `json:"filesystem"`
	Git        GitPolicy                 `json:"git"`
	Model      string                    `json:"model,omitempty"`
	Network    EffectiveNetworkPolicy    `json:"network"`
	Profile    string                    `json:"profile"`
	Prompt     string                    `json:"prompt,omitempty"`
	Provider   ProviderKind              `json:"provider"`
	Tools      ToolPolicy                `json:"tools"`

	// UserHome Canonical absolute host home used to validate resolved authored paths.
	UserHome string `json:"user_home"`

	// Workspace Canonical absolute workspace directory.
	Workspace string `json:"workspace"`
}

// GitIsolation Whether the sandbox may mutate the resolved Git common directory.
type GitIsolation string

// GitPolicy defines model for GitPolicy.
type GitPolicy struct {
	// Isolation Whether the sandbox may mutate the resolved Git common directory.
	Isolation         *GitIsolation             `json:"isolation,omitempty"`
	Operations        map[string]PolicyDecision `json:"operations,omitempty"`
	ProtectedBranches *[]string                 `json:"protected_branches,omitempty"`
}

// IntegrationPolicy defines model for IntegrationPolicy.
type IntegrationPolicy struct {
	// Decision Whether a capability proceeds, asks the user, or is refused.
	Decision PolicyDecision `json:"decision"`

	// MutationDecision Whether a capability proceeds, asks the user, or is refused.
	MutationDecision *PolicyDecision `json:"mutation_decision,omitempty"`
}

// MCPServerPolicy defines model for MCPServerPolicy.
type MCPServerPolicy struct {
	// Decision Whether a capability proceeds, asks the user, or is refused.
	Decision PolicyDecision           `json:"decision"`
	Tools    map[string]MCPToolPolicy `json:"tools,omitempty"`

	// Transport Execution boundary used by this server.
	Transport *MCPServerPolicyTransport `json:"transport,omitempty"`
}

// MCPServerPolicyTransport Execution boundary used by this server.
type MCPServerPolicyTransport string

// MCPToolPolicy defines model for MCPToolPolicy.
type MCPToolPolicy struct {
	// Decision Whether a capability proceeds, asks the user, or is refused.
	Decision    PolicyDecision `json:"decision"`
	Description string         `json:"description,omitempty"`
}

// NetworkMode Enforcement posture for sandboxed outbound connections.
type NetworkMode string

// PolicyDecision Whether a capability proceeds, asks the user, or is refused.
type PolicyDecision string

// Profile Portable user-authored profile stored in VS Code configuration.
type Profile struct {
	// Effort Provider-specific reasoning effort.
	Effort     string                    `json:"effort,omitempty"`
	Filesystem *AuthoredFilesystemPolicy `json:"filesystem,omitempty"`
	Git        *GitPolicy                `json:"git,omitempty"`
	Model      string                    `json:"model,omitempty"`
	Network    *AuthoredNetworkPolicy    `json:"network,omitempty"`
	Prompt     string                    `json:"prompt,omitempty"`
	Provider   *ProviderKind             `json:"provider,omitempty"`
	Tools      *ToolPolicy               `json:"tools,omitempty"`
}

// ProviderKind defines model for ProviderKind.
type ProviderKind string

// ToolPolicy defines model for ToolPolicy.
type ToolPolicy struct {
	Core         *CoreToolPolicy              `json:"core,omitempty"`
	Integrations map[string]IntegrationPolicy `json:"integrations,omitempty"`
	Mcp          map[string]MCPServerPolicy   `json:"mcp,omitempty"`
}
