package paths

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"

	"braces.dev/errtrace"
)

var cwdProjectRoot *string

// NormalizePath returns an absolute, symlink-resolved path with forward slashes.
func NormalizePath(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", errtrace.Wrap(err)
	}
	eval, err := filepath.EvalSymlinks(abs)
	var final string
	if err != nil {
		// If the path doesn't exist, EvalSymlinks fails. We still want a normalized path.
		final = abs
	} else {
		final = eval
	}

	return filepath.ToSlash(final), nil
}

// ResolveUserPath turns a path a human typed into an absolute one, the way a
// shell would: "~" and "~/x" expand to the home directory. A relative path
// ("code/hydra", "./hydra") resolves against HOME too, NOT against the process
// working directory - the person typing it is in a browser and has no idea what
// the daemon's cwd is, whereas home is the one directory they can reason about.
//
// "~user/..." (another user's home) is not supported and is returned unchanged,
// so the caller's "no such directory" error names what was typed instead of a
// nonsense $HOME/~user path.
func ResolveUserPath(p string) string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = ""
	}
	return resolveUserPath(p, home)
}

// resolveUserPath is ResolveUserPath with an explicit home, split out for
// testing. An empty home falls back to filepath.Abs (process cwd) - the best
// that can be done when the OS won't say where home is.
func resolveUserPath(p, home string) string {
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	if home != "" {
		if p == "~" {
			return filepath.Clean(home)
		}
		if strings.HasPrefix(p, "~/") || (os.PathSeparator == '\\' && strings.HasPrefix(p, `~\`)) {
			return filepath.Clean(filepath.Join(home, p[2:]))
		}
	}
	// "~user" or a bare "~" with no home: leave it alone rather than inventing a path.
	if strings.HasPrefix(p, "~") {
		return p
	}
	if filepath.IsAbs(p) {
		return filepath.Clean(p)
	}
	if home != "" {
		return filepath.Clean(filepath.Join(home, p))
	}
	if abs, err := filepath.Abs(p); err == nil {
		return abs
	}
	return filepath.Clean(p)
}

// ComparePaths compares two paths using platform-appropriate rules.
// On Windows it is case-insensitive; on other platforms it is case-sensitive.
func ComparePaths(p1, p2 string) bool {
	if runtime.GOOS == "windows" {
		return strings.EqualFold(p1, p2)
	}
	return p1 == p2
}

// GetProjectRootFromCwd gets the git directory from the current directory
func GetProjectRootFromCwd() (string, error) {
	if cwdProjectRoot != nil {
		return *cwdProjectRoot, nil
	}
	cwd, err := os.Getwd()
	if err != nil {
		return "", errtrace.Wrap(fmt.Errorf("get working directory: %w", err))
	}
	projectRoot, err := GetProjectRoot(cwd)
	if err != nil {
		return "", errtrace.Wrap(err)
	}
	norm, err := NormalizePath(projectRoot)
	if err != nil {
		return "", errtrace.Wrap(err)
	}
	cwdProjectRoot = &norm
	return norm, nil
}

// GetProjectRoot returns the root of the git repository containing dir.
func GetProjectRoot(dir string) (string, error) {
	out, err := exec.Command("git", "-C", dir, "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", errtrace.Wrap(fmt.Errorf("git open: not a git repository"))
	}
	return errtrace.Wrap2(NormalizePath(strings.TrimRight(string(out), "\n")))
}

func GetHydraDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(projectRoot, ".hydra")
}

// GetDeployConfigPath returns the path to the project's deploy.toml. It holds
// the remote-access auth key (and optional listen address) and is NOT committed
// (it is .gitignored): it contains a secret. It sits at the .hydra top level
// next to config.toml rather than under .hydra/local, because it is a
// hand-managed/generated config file, not generated runtime state.
func GetDeployConfigPath(projectRoot string) string {
	return filepath.Join(GetHydraDirFromProjectRoot(projectRoot), "deploy.toml")
}

// GetProjectConfigLocalPath returns the path to the project's config.local.toml:
// an untracked (.gitignored, next to deploy.toml), non-secret, per-user-per-project
// override layer with the same schema as config.toml. It is loaded as the fourth
// config merge layer (defaults -> user -> project -> project-local) and, being
// host-side and editable only by the user, is as trusted as the root config (it
// participates in the unsafe_host trusted set). See docs/non-local-integration.md
func GetProjectConfigLocalPath(projectRoot string) string {
	return filepath.Join(GetHydraDirFromProjectRoot(projectRoot), "config.local.toml")
}

// GetNgrokConfigPath returns the path to the project's ngrok.yml, generated by
// `mage deploy:ngrok`. Like deploy.toml it sits at the .hydra top level and is
// NOT committed (it is .gitignored): it embeds the ngrok authtoken.
func GetNgrokConfigPath(projectRoot string) string {
	return filepath.Join(GetHydraDirFromProjectRoot(projectRoot), "ngrok.yml")
}

// GetHydraLocalDirFromProjectRoot returns .hydra/local, the single parent holding
// every generated, never-committed thing (worktrees, the SQLite DB, caches, COW
// layers, the per-head tmp dir, ...). Only .hydra/config.toml lives at the .hydra
// top level. A single "*" .gitignore at this .hydra/local root ignores the whole
// subtree, so no individual subdirectory carries its own .gitignore. See
// MigrateHydraLayout for the one-time move of projects created under the old flat
// layout.
func GetHydraLocalDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraDirFromProjectRoot(projectRoot), "local")
}

func GetWorktreesDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "worktrees")
}

func GetWorktreeDirFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetWorktreesDirFromProjectRoot(projectRoot), id)
}

func GetStateDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "state")
}

// GetArtifactsDirFromProjectRoot returns the (gitignored) directory holding
// generated diff artifacts (screenshots etc.) and their ephemeral checkouts.
func GetArtifactsDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "artifacts")
}

// GetTestsDirFromProjectRoot returns the (gitignored) directory holding per-head
// test-runner results (TestReport meta.json + build logs) and their ephemeral
// checkouts. Mirrors GetArtifactsDirFromProjectRoot for the test gate (see PLAN
// #68); kept separate so the two generators don't share a slot pool dir.
func GetTestsDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "tests")
}

// GetUploadsDirFromProjectRoot returns the (gitignored) directory holding files
// pasted/attached to prompts. It sits under .hydra/local so it's readable
// read-only inside agent sandboxes at the same absolute path.
func GetUploadsDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "uploads")
}

// GetCacheDirFromProjectRoot returns the (gitignored) directory holding generated
// caches (e.g. the captured Gemini default system prompt, keyed by CLI version).
func GetCacheDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "cache")
}

func GetDBPathFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetStateDirFromProjectRoot(projectRoot), "db.sqlite3")
}

func GetStatusDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "status")
}

// GetNamespaceSocketDirFromProjectRoot returns the (gitignored) directory holding
// a head's namespace-host control socket. Like the other generated dirs it sits
// under .hydra/local; the sockets themselves are recreated on each launch.
func GetNamespaceSocketDirFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "ns", id)
}

func GetStatusJsonFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetStatusDirFromProjectRoot(projectRoot), id+".json")
}

// The per-head companion state (status log, build log, review, sub-agents,
// queue) each live in their OWN directory keyed by the bare id, rather than as
// status/<id>_<suffix> siblings of status.json. Keying the whole filename by the
// id makes them collision-proof: a head id may contain "_" (headIDRe), so a
// suffix like status/<id>_review.json could otherwise alias the status file of a
// head literally named "<id>_review" (see PLAN #26). status.json stays the base
// name in status/ (nothing else shares that dir now, so it can't collide).
func GetStatusLogDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "status-log")
}
func GetStatusLogFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetStatusLogDirFromProjectRoot(projectRoot), id+".jsonl")
}

func GetBuildLogDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "build-log")
}

// GetChatQueueDirFromProjectRoot returns the directory holding per-head chat
// message queues. A dedicated dir keyed by the bare id (rather than a
// status/<id>_queue.json suffix) keeps the id the whole filename, so no head id
// ending in "_queue" can collide with another head's file.
func GetChatQueueDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "queue")
}

// GetChatQueueJsonFromProjectRoot returns the per-head file holding a chat-mode
// head's queued (not-yet-sent) user messages, so the daemon can hold them while
// a turn runs and replay them to a (re)attaching client, surviving a daemon
// restart. Lives at .hydra/local/queue/<id>.json.
func GetChatQueueJsonFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetChatQueueDirFromProjectRoot(projectRoot), id+".json")
}

// GetChatEventsDirFromProjectRoot returns the directory containing the
// provider-neutral, sequenced chat event logs. Each head owns one JSONL file.
func GetChatEventsDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "chat-events")
}

func GetChatEventsJSONLFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetChatEventsDirFromProjectRoot(projectRoot), id+".jsonl")
}

// GetChatStateDirFromProjectRoot returns the directory containing materialized
// chat-state checkpoints. They are kept separate from event logs so a partial
// checkpoint replacement can never damage durable history.
func GetChatStateDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "chat-state")
}

func GetChatStateJSONFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetChatStateDirFromProjectRoot(projectRoot), id+".json")
}

func GetBuildLogFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetBuildLogDirFromProjectRoot(projectRoot), id+".log")
}

// GetChatThinkingDirFromProjectRoot holds the per-head sidecars recording each
// thinking block's Hydra-measured duration (keyed by Claude message id), so a
// reload/resume can show "Thought for Xs" without the browser timing it. Lives
// at .hydra/local/thinking/.
func GetChatThinkingDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "thinking")
}

// GetChatThinkingJsonFromProjectRoot returns a chat-mode head's thinking-duration
// sidecar, at .hydra/local/thinking/<id>.json.
func GetChatThinkingJsonFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetChatThinkingDirFromProjectRoot(projectRoot), id+".json")
}

// GetReviewJsonFromProjectRoot returns the per-head review file the MR lifecycle
// watcher writes (status + unresolved discussions) and the in-sandbox `hydra mcp`
// server reads for get_review_status / get_review_comments
// (docs/non-local-integration.md). Per-head by construction: it is bound only into that head's sandbox, so
// the agent's identity comes from the channel, never a self-reported id. Lives
// at .hydra/local/review/<id>.json.
func GetReviewDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "review")
}
func GetReviewJsonFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetReviewDirFromProjectRoot(projectRoot), id+".json")
}

// GetReviewCheckoutDirFromProjectRoot returns the persistent detached worktree a
// head's review slot works in (docs/review-agent.md). Distinct from
// GetReviewDirFromProjectRoot above, which is the forge MR state - unrelated.
//
// Deliberately NOT a checkout.Pool slot. A pooled slot is recycled between runs,
// and a Claude conversation is keyed by its working directory
// (~/.claude/projects/<slug(path)>), so a moving path would hand the reviewer a
// fresh transcript on every re-acquire - a reviewer that forgets everything. A
// stable path also means exactly one session ever writes that transcript dir,
// which is what makes the reviewer's own `--continue` resume unambiguous (the
// head's is not, which is why it needs an explicit session id). Lives at
// .hydra/local/review-checkouts/<id>/.
func GetReviewCheckoutsBaseDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "review-checkouts")
}
func GetReviewCheckoutDirFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetReviewCheckoutsBaseDirFromProjectRoot(projectRoot), id)
}

// GetSubagentsDirFromProjectRoot returns the per-head directory tracking the
// head's currently-live Claude sub-agents (Task tool). trigger-hook drops a
// marker file per running sub-agent so the main agent's Stop hook can tell a
// genuine finish from "the turn ended but sub-agents are still working". Lives
// at .hydra/local/subagents/<id>/.
func GetSubagentsBaseDirFromProjectRoot(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "subagents")
}
func GetSubagentsDirFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetSubagentsBaseDirFromProjectRoot(projectRoot), id)
}

// GetApprovalsDirFromProjectRoot returns the per-head directory used for the
// security-gate "ask" round-trip: the in-sandbox hook writes approval requests
// here (the dir is made writable at its real host path, like status.json) and
// the daemon writes back decisions. Lives under .hydra/local/approvals/<id>.
func GetApprovalsDirFromProjectRoot(projectRoot, id string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "approvals", id)
}

// GetReviewThreadsJson returns the per-head cache of the MR's review threads,
// written whenever they are read from the forge so the diff viewer still renders
// the conversation when a live read fails. Lives at
// .hydra/local/review-threads/<id>.json.
func GetReviewThreadsJson(projectRoot, id string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "review-threads", id+".json")
}

// GetReviewNotesJson returns the per-head store of LOCAL-ONLY review notes -
// replies that live in Hydra and are never sent to the forge (an agent's answer
// to a reviewer, or a note to self). Lives at
// .hydra/local/review-notes/<id>.json.
func GetReviewNotesJson(projectRoot, id string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "review-notes", id+".json")
}

// GetReviewReqRootDir returns the parent dir holding every head's review-refresh
// channel (.hydra/local/review-req). The daemon's review-request watcher scans it
// to find heads asking for a forge refresh.
func GetReviewReqRootDir(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "review-req")
}

// GetReviewReqDir returns the per-head directory used for the on-demand review
// refresh round-trip: the in-sandbox review tools write a request here (the dir
// is made writable at its real host path, like the approvals dir) and the daemon
// re-reads the MR from the forge, rewrites the head's review file and writes back
// a result. Lives under .hydra/local/review-req/<id>.
func GetReviewReqDir(projectRoot, id string) string {
	return filepath.Join(GetReviewReqRootDir(projectRoot), id)
}

// GetGitopsRootDir returns the parent dir holding every head's host-mediated git
// channel (.hydra/local/gitops). The daemon's gitops watcher scans it to find
// heads with pending git-operation requests.
func GetGitopsRootDir(projectRoot string) string {
	return filepath.Join(GetHydraLocalDirFromProjectRoot(projectRoot), "gitops")
}

// GetGitopsDir returns the per-head directory used for the host-mediated git
// round-trip (git_isolation readonly): the in-sandbox git tools write a request
// here (the dir is made writable at its real host path, like the approvals dir)
// and the daemon's gitops watcher writes back the result. Lives under
// .hydra/local/gitops/<id>.
func GetGitopsDir(projectRoot, id string) string {
	return filepath.Join(GetGitopsRootDir(projectRoot), id)
}

// WriteFileIfChanged writes content to path only when it differs from the existing file.
// Reports whether the file was (over)written.
func WriteFileIfChanged(path, content string, perm os.FileMode) error {
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == content {
		return nil // already up to date
	}
	return errtrace.Wrap(os.WriteFile(path, []byte(content), perm))
}

// EnsureHydraLocalIgnored creates dir (a generated directory under .hydra/local)
// and guarantees the enclosing .hydra/local carries a single "*" .gitignore. That
// one top-level ignore covers the whole generated subtree - worktrees, state,
// caches, COW layers, the per-head tmp dir, ... - so individual subdirectories no
// longer need their own .gitignore. When dir is not under a .hydra/local ancestor
// (only happens in tests), the .gitignore is written into dir itself as a fallback.
func EnsureHydraLocalIgnored(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return errtrace.Wrap(fmt.Errorf("create dir: %w: %s", err, dir))
	}
	target := hydraLocalDirOf(dir)
	if target == "" {
		target = dir
	}
	return errtrace.Wrap(writeGitignoreAll(target))
}

// writeGitignoreAll creates dir and drops a "*" .gitignore in it if one is not
// already present (idempotent), so the whole subtree stays out of git status.
func writeGitignoreAll(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return errtrace.Wrap(fmt.Errorf("create dir: %w: %s", err, dir))
	}
	gitignorePath := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte("*\n"), 0o644); err != nil {
			return errtrace.Wrap(fmt.Errorf("create .gitignore: %w: %s", err, gitignorePath))
		}
	}
	return nil
}

// hydraLocalDirOf returns the ".hydra/local" ancestor of dir (inclusive), or ""
// if dir is not nested under one. The match is purely textual: a path element
// named "local" whose parent element is named ".hydra".
func hydraLocalDirOf(dir string) string {
	d := filepath.Clean(dir)
	for {
		if filepath.Base(d) == "local" && filepath.Base(filepath.Dir(d)) == ".hydra" {
			return d
		}
		parent := filepath.Dir(d)
		if parent == d {
			return "" // reached the filesystem root without a match
		}
		d = parent
	}
}

// hydraLocalSubdirs are the generated .hydra subdirectories that used to sit at
// the .hydra top level and now live under .hydra/local. MigrateHydraLayout moves
// any it finds at the old location.
var hydraLocalSubdirs = []string{"worktrees", "state", "artifacts", "uploads", "status", "cache", "cow", "ns"}

// MigrateHydraLayout moves a project created under the old flat layout
// (.hydra/<dir>) into the consolidated one (.hydra/local/<dir>). It is idempotent
// and best-effort per directory: a directory already present at the new location
// is left untouched. Worktrees record absolute git metadata links, so after
// moving them we run `git worktree repair` to re-point the registrations.
//
// Called from db.Open (covers the boot project + CLI commands) and per-project at
// daemon boot / on AddProject, so every project is migrated before its worktrees
// or DB are used.
func MigrateHydraLayout(projectRoot string) error {
	hydra := GetHydraDirFromProjectRoot(projectRoot)
	local := GetHydraLocalDirFromProjectRoot(projectRoot)

	movedWorktrees := false
	for _, name := range hydraLocalSubdirs {
		oldPath := filepath.Join(hydra, name)
		newPath := filepath.Join(local, name)
		info, err := os.Stat(oldPath)
		if err != nil || !info.IsDir() {
			continue // nothing at the old location
		}
		if _, err := os.Stat(newPath); err == nil {
			// Already migrated (or a partial state) - don't clobber the new copy.
			log.Printf("warn: hydra layout: both %s and %s exist; leaving the old one in place", oldPath, newPath)
			continue
		}
		if err := os.MkdirAll(local, 0o755); err != nil {
			return errtrace.Wrap(fmt.Errorf("create %s: %w", local, err))
		}
		if err := os.Rename(oldPath, newPath); err != nil {
			return errtrace.Wrap(fmt.Errorf("move %s -> %s: %w", oldPath, newPath, err))
		}
		log.Printf("hydra layout: migrated .hydra/%s -> .hydra/local/%s in %s", name, name, projectRoot)
		if name == "worktrees" {
			movedWorktrees = true
		}
	}

	if movedWorktrees {
		if err := repairMovedWorktrees(projectRoot, filepath.Join(local, "worktrees")); err != nil {
			// Non-fatal: the worktrees still work; only their git metadata links are
			// stale until repaired. Surface it so it can be fixed manually if needed.
			log.Printf("warn: hydra layout: git worktree repair in %s: %v", projectRoot, err)
		}
	}

	// Migrate Claude session-history dirs to follow the worktree move. This runs on
	// every call (not gated on movedWorktrees) and independently of it: projects
	// migrated by an earlier build moved their worktrees but left these dirs at the
	// old slug, so resume was broken with no remaining trigger. It's idempotent and
	// a cheap no-op once every head's history sits at the new slug.
	worktreesDir := filepath.Join(local, "worktrees")
	if info, err := os.Stat(worktreesDir); err == nil && info.IsDir() {
		if err := migrateClaudeSessionDirs(projectRoot, worktreesDir); err != nil {
			// Non-fatal: only Claude's conversation-resume (--continue) for moved
			// heads is affected until their session dirs follow the worktree move.
			log.Printf("warn: hydra layout: migrate claude session dirs in %s: %v", projectRoot, err)
		}
	}

	// Consolidate ignoring at the .hydra/local root: a single "*" .gitignore there
	// covers the whole generated subtree (worktrees, state, caches, tmp, ...). Make
	// sure it exists, then drop any now-redundant per-subdir .gitignore files that
	// older builds left behind.
	if err := writeGitignoreAll(local); err != nil {
		return errtrace.Wrap(err)
	}
	removeRedundantSubdirGitignores(local)
	return nil
}

// removeRedundantSubdirGitignores deletes the per-subdirectory "*" .gitignore
// files that older builds dropped in each generated dir under .hydra/local. The
// single .gitignore at the .hydra/local root now ignores the whole subtree, so
// these are redundant. Best-effort and conservative: it only removes a direct
// child directory's .gitignore whose content is exactly "*" (never one a user or
// tool wrote with other rules).
func removeRedundantSubdirGitignores(local string) {
	entries, err := os.ReadDir(local)
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		gi := filepath.Join(local, e.Name(), ".gitignore")
		content, err := os.ReadFile(gi)
		if err != nil {
			continue // no .gitignore (or unreadable) - nothing to remove
		}
		if strings.TrimSpace(string(content)) != "*" {
			continue // a real ignore file, leave it alone
		}
		if err := os.Remove(gi); err != nil {
			log.Printf("warn: hydra layout: remove redundant %s: %v", gi, err)
		}
	}
}

// repairMovedWorktrees re-points the git worktree registrations after their
// directories were moved under .hydra/local. `git worktree repair <path>...`,
// run from the main worktree, rewrites the stale absolute gitdir links.
func repairMovedWorktrees(projectRoot, worktreesDir string) error {
	entries, err := os.ReadDir(worktreesDir)
	if err != nil {
		return errtrace.Wrap(err)
	}
	args := []string{"-C", projectRoot, "worktree", "repair"}
	for _, e := range entries {
		if e.IsDir() {
			args = append(args, filepath.Join(worktreesDir, e.Name()))
		}
	}
	if len(args) == 4 { // no worktree dirs to repair
		return nil
	}
	if out, err := exec.Command("git", args...).CombinedOutput(); err != nil {
		return errtrace.Wrap(fmt.Errorf("git worktree repair: %w: %s", err, strings.TrimSpace(string(out))))
	}
	return nil
}

// migrateClaudeSessionDirs renames each head's Claude Code session-history
// directory to follow its worktree's move under .hydra/local. Claude derives the
// dir name from the worktree's absolute path (its cwd) via ClaudeProjectsSlug and
// stores it at ~/.claude/projects/<slug>; once the worktree moves from
// .hydra/worktrees/<id> to .hydra/local/worktrees/<id> the old slug no longer
// matches, so `claude --continue` reports "No conversation found to continue".
// Renaming the dir to the new slug restores resume for pre-move heads.
//
// Best-effort: per-head failures are logged and skipped. Other agent types key
// their history differently (or not by cwd), so only Claude's dir is migrated -
// mirroring removeClaudeSessionDir, which is likewise Claude-only.
func migrateClaudeSessionDirs(projectRoot, newWorktreesDir string) error {
	u, err := user.Current()
	if err != nil || u.HomeDir == "" {
		return errtrace.Wrap(fmt.Errorf("resolve home: %w", err))
	}
	// Compute slugs from the symlink-resolved project root so they match the cwd
	// Claude actually recorded; the slug is purely textual, so a now-missing old
	// worktree path still encodes correctly.
	root, nerr := NormalizePath(projectRoot)
	if nerr != nil {
		root = projectRoot
	}
	oldWorktreesDir := filepath.Join(GetHydraDirFromProjectRoot(root), "worktrees")
	projectsDir := filepath.Join(u.HomeDir, ".claude", "projects")
	return errtrace.Wrap(migrateClaudeSessionDirsIn(projectsDir, oldWorktreesDir, newWorktreesDir))
}

// migrateClaudeSessionDirsIn is the testable core of migrateClaudeSessionDirs: it
// renames ~/.claude/projects/<oldSlug> to <newSlug> for every head directory found
// under newWorktreesDir, given an explicit projects dir.
func migrateClaudeSessionDirsIn(projectsDir, oldWorktreesDir, newWorktreesDir string) error {
	entries, err := os.ReadDir(newWorktreesDir)
	if err != nil {
		return errtrace.Wrap(err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		id := e.Name()
		oldSlug := ClaudeProjectsSlug(filepath.Join(oldWorktreesDir, id))
		newSlug := ClaudeProjectsSlug(filepath.Join(newWorktreesDir, id))
		if oldSlug == newSlug {
			continue
		}
		oldDir := filepath.Join(projectsDir, oldSlug)
		newDir := filepath.Join(projectsDir, newSlug)
		if info, serr := os.Stat(oldDir); serr != nil || !info.IsDir() {
			continue // this head has no Claude history at the old location
		}
		if _, serr := os.Stat(newDir); serr == nil {
			log.Printf("warn: hydra layout: both %s and %s exist; leaving claude session dir in place", oldDir, newDir)
			continue
		}
		if err := os.Rename(oldDir, newDir); err != nil {
			log.Printf("warn: hydra layout: move claude session dir %s -> %s: %v", oldDir, newDir, err)
			continue
		}
		log.Printf("hydra layout: migrated claude session dir for head %s", id)
	}
	return nil
}

// ClaudeProjectsSlug mirrors how Claude Code encodes a working directory into its
// ~/.claude/projects/<slug> folder name: every character that is not an ASCII
// letter or digit becomes '-' (no collapsing of runs), so e.g.
// /home/u/code/hydra/.hydra/local/worktrees/x ->
// -home-u-code-hydra--hydra-local-worktrees-x.
// ClaudeProjectDir resolves the directory where Claude Code records a worktree's
// transcripts (~/.claude/projects/<slug>), or "" when it can't be determined.
func ClaudeProjectDir(worktree string) string {
	home, err := os.UserHomeDir()
	if err != nil || worktree == "" {
		return ""
	}
	return filepath.Join(home, ".claude", "projects", ClaudeProjectsSlug(worktree))
}

func ClaudeProjectsSlug(p string) string {
	b := make([]byte, len(p))
	for i := 0; i < len(p); i++ {
		c := p[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
			b[i] = c
		default:
			b[i] = '-'
		}
	}
	return string(b)
}
