package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"

	"braces.dev/errtrace"
	"github.com/BurntSushi/toml"
	"github.com/trolleyman/hydra/internal/paths"
)

// DeployConfig is the project's remote-access deployment config, stored
// (uncommitted, .gitignored) at .hydra/deploy.toml. It exists so Hydra can be
// reached safely from outside the machine (e.g. a phone): loopback connections
// are always trusted, but a non-localhost request must present AuthKey.
//
// It is deliberately separate from config.toml: config.toml is committed and
// shapes agent/sandbox behaviour, whereas deploy.toml holds a per-machine
// secret and must never enter git.
type DeployConfig struct {
	// AuthKey is the shared secret required by non-localhost clients. Empty
	// disables auth entirely (the previous behaviour: localhost-only access).
	AuthKey string `toml:"auth_key"`
	// ListenAddr overrides the web server's bind address (host:port). Empty
	// keeps the default localhost:8080 (unreachable from other machines). Set
	// e.g. "0.0.0.0:8080" to expose the UI on the LAN, where AuthKey then
	// gates every non-loopback request. HYDRA_API_ADDR still overrides this.
	ListenAddr string `toml:"listen_addr"`
}

// GenerateAuthKey returns a fresh, URL-safe random key (32 bytes of entropy)
// suitable for use as DeployConfig.AuthKey.
func GenerateAuthKey() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", errtrace.Wrap(fmt.Errorf("generate auth key: %w", err))
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// LoadDeploy reads .hydra/deploy.toml for the project. A missing file is not an
// error — it returns the zero DeployConfig (auth disabled, default listen addr).
func LoadDeploy(projectRoot string) (DeployConfig, error) {
	var cfg DeployConfig
	if projectRoot == "" {
		return cfg, nil
	}
	path := paths.GetDeployConfigPath(projectRoot)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, errtrace.Wrap(fmt.Errorf("read deploy config: %s: %w", path, err))
	}
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return cfg, errtrace.Wrap(fmt.Errorf("parse deploy config: %s: %w", path, err))
	}
	return cfg, nil
}

// SaveDeploy writes the project's .hydra/deploy.toml with 0600 permissions
// (it holds a secret). The parent directory is created if needed.
func SaveDeploy(projectRoot string, cfg DeployConfig) error {
	path := paths.GetDeployConfigPath(projectRoot)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return errtrace.Wrap(fmt.Errorf("create deploy config parent: %s: %w", path, err))
	}
	content := renderDeploy(cfg)
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return errtrace.Wrap(fmt.Errorf("save deploy config: %s: %w", path, err))
	}
	return nil
}

// renderDeploy emits a small, commented deploy.toml. It is written by hand
// (rather than via toml.Marshal) so the generated file documents itself.
func renderDeploy(cfg DeployConfig) string {
	s := "# Hydra deployment config — generated by `mage deploy:setup`.\n" +
		"# This file holds a secret and is .gitignored; do NOT commit it.\n" +
		"#\n" +
		"# Localhost connections are always trusted. Any non-localhost client must\n" +
		"# present auth_key (via the web login screen, which stores it in a cookie,\n" +
		"# or an `Authorization: Bearer <auth_key>` header for API clients).\n" +
		"\n"
	s += "auth_key = " + tomlStringValue(cfg.AuthKey) + "\n"
	s += "\n" +
		"# Bind address for the web UI. Default (commented) is localhost:8080, which\n" +
		"# is only reachable from this machine. Set 0.0.0.0:8080 to expose it on the\n" +
		"# network so you can reach it from e.g. your phone — auth_key then guards\n" +
		"# every non-localhost request.\n"
	if cfg.ListenAddr != "" {
		s += "listen_addr = " + tomlStringValue(cfg.ListenAddr) + "\n"
	} else {
		s += "# listen_addr = \"0.0.0.0:8080\"\n"
	}
	return s
}
