package config

import (
	"fmt"
	"os"
	"strings"

	"braces.dev/errtrace"
	"github.com/trolleyman/hydra/internal/paths"
)

// RenderNgrokYAML renders an ngrok v3 agent config that publishes the Hydra web
// UI running on the given local port. Security lives entirely at the ngrok
// layer, mirroring the reference deployment: every request must pass Google
// OAuth, and any identity whose email is not AllowedEmail is denied with a 403.
// Because ngrok dials the local port, Hydra can stay bound to localhost.
func RenderNgrokYAML(cfg NgrokConfig, localPort string) string {
	// Hand-rendered (not marshalled) so the indentation matches ngrok's expected
	// v3 shape exactly and the file documents itself. Values are user-supplied
	// but constrained (authtoken/domain/email/name), so single-quote them and
	// escape embedded single quotes for the YAML flow scalars.
	q := func(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
	return "" +
		"version: \"3\"\n" +
		"# Generated by `mage deploy:ngrok` - do NOT commit (embeds your authtoken).\n" +
		"agent:\n" +
		"    authtoken: " + q(cfg.Authtoken) + "\n" +
		"endpoints:\n" +
		"  - name: " + q(cfg.Name) + "\n" +
		"    url: https://" + cfg.Domain + "\n" +
		"    upstream:\n" +
		"      url: " + localPort + "\n" +
		"    traffic_policy:\n" +
		"      on_http_request:\n" +
		"        # Authenticate with Google OAuth\n" +
		"        - actions:\n" +
		"            - type: oauth\n" +
		"              config:\n" +
		"                provider: google\n" +
		"        # Only allow this single Google account through\n" +
		"        - expressions:\n" +
		"            - \"actions.ngrok.oauth.identity.email != " + q(cfg.AllowedEmail) + "\"\n" +
		"          actions:\n" +
		"            - type: deny\n" +
		"              config:\n" +
		"                status_code: 403\n"
}

// WriteNgrokConfig renders and writes .hydra/ngrok.yml for the project with 0600
// permissions (it embeds the authtoken). The parent .hydra dir is assumed to
// exist (SaveDeploy created it). Returns the path written.
func WriteNgrokConfig(projectRoot string, cfg NgrokConfig, localPort string) (string, error) {
	path := paths.GetNgrokConfigPath(projectRoot)
	if err := os.WriteFile(path, []byte(RenderNgrokYAML(cfg, localPort)), 0600); err != nil {
		return "", errtrace.Wrap(fmt.Errorf("write ngrok config: %s: %w", path, err))
	}
	return path, nil
}
