/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId/index'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/project.$projectId/settings'
import { Route as ProjectProjectIdAgentAgentIdRouteImport } from './routes/project.$projectId/agent.$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdAgentAgentIdRoute =
  ProjectProjectIdAgentAgentIdRouteImport.update({
    id: '/agent/$agentId',
    path: '/agent/$agentId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/agent/$agentId': typeof ProjectProjectIdAgentAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/agent/$agentId': typeof ProjectProjectIdAgentAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/agent/$agentId': typeof ProjectProjectIdAgentAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/settings'
    | '/project/$projectId/'
    | '/project/$projectId/agent/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/project/$projectId/settings'
    | '/project/$projectId'
    | '/project/$projectId/agent/$agentId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/settings'
    | '/project/$projectId/'
    | '/project/$projectId/agent/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/settings': {
      id: '/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/agent/$agentId': {
      id: '/project/$projectId/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/project/$projectId/agent/$agentId'
      preLoaderRoute: typeof ProjectProjectIdAgentAgentIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdAgentAgentIdRoute: typeof ProjectProjectIdAgentAgentIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdAgentAgentIdRoute: ProjectProjectIdAgentAgentIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
