/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentsRouteImport } from './routes/_agents'
import { Route as AgentsIndexRouteImport } from './routes/_agents/index'
import { Route as AgentsAgentAgentIdRouteImport } from './routes/_agents/agent.$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/_agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentAgentIdRoute = AgentsAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AgentsIndexRoute
  '/settings': typeof SettingsRoute
  '/agent/$agentId': typeof AgentsAgentAgentIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof AgentsIndexRoute
  '/agent/$agentId': typeof AgentsAgentAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_agents': typeof AgentsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_agents/': typeof AgentsIndexRoute
  '/_agents/agent/$agentId': typeof AgentsAgentAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/agent/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/agent/$agentId'
  id:
    | '__root__'
    | '/_agents'
    | '/settings'
    | '/_agents/'
    | '/_agents/agent/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentsRoute: typeof AgentsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agents': {
      id: '/_agents'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_agents/': {
      id: '/_agents/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_agents/agent/$agentId': {
      id: '/_agents/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentsAgentAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsAgentAgentIdRoute: typeof AgentsAgentAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsAgentAgentIdRoute: AgentsAgentAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AgentsRoute: AgentsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
