import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `dist` is build output; `src/api` is generated by openapi-typescript-codegen
  // (each file carries its own blanket `/* eslint-disable */`), so linting it only
  // produces "unused disable directive" noise — skip it wholesale.
  globalIgnores(['dist', 'src/api']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // TanStack Router route files are `export const Route = createFileRoute(...)(...)`
      // (or createRootRoute(...)) alongside a local page component. eslint-plugin-react-refresh
      // v0.5 stopped recognizing those route-factory calls as component exports, so register
      // them as HOCs - that keeps `Route` counted as the file's component export and Fast
      // Refresh happy, without splitting every route into two files.
      'react-refresh/only-export-components': ['error', { allowConstantExport: true, extraHOCs: ['createFileRoute', 'createRootRoute'] }],
    },
  },
])
